### ISSUE TITLE
JsonSerializable: supported nested json objects

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/json_serializable#11]
_From @kevmoo on June 24, 2015 3:1_

- [x] Single items
- [x] Items in a List
- [ ] Items as values in a Map

_Copied from original issue: dart-lang/source_gen#52_

**Comment by DanielEberl** [comment]
How can this still not be addressed?

**Comment by kevmoo** [comment]
> How can this still not be addressed?

We have not received a pull request fixing it yet. This package is supported at a "best effort" level.

**Comment by kevmoo** [comment]
And honestly, I'm not sure what it means any more...

**Comment by kevmoo** [comment]
I believe it IS fixed!

**Comment by eseidel** [comment]
For those who find this and wonder "how", @JsonSerializable(explicitToJson: true) is the magic.  Without the explicitToJson it won't call .toJson() recursively:
https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html

**Comment by kevmoo** [comment]
Yup! This setup is designed for https://api.dart.dev/stable/2.17.3/dart-convert/jsonEncode.html and friends which call `toJson` for you.

Interesting note: this is a dynamic invocation, which we'd like to avoid in many cases. So I may change this behavior in the future. We'll see...
