### ISSUE TITLE
Add annotation to ignore a field

### ISSUE THREAD

**Issue by supermuka** [dart-lang/json_serializable#110]
It would be useful (at least for me) to have an annotation to _ignore_ the serialization of certain fields.

@JsonSerializable()
Class Person {
  
 **@JsonKey(ignore: true)**
  final bool isNew;

}

**Comment by kevmoo** [comment]
ack! Pull requests welcome...

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/json_serializable/commit/a4b377c7e081cfd5b94a41aec8362d7393d0dafb
