### ISSUE TITLE
Support Generics?

### ISSUE THREAD

**Issue by xiang23** [dart-lang/json_serializable#116]
I get error when  used generics.

**Comment by kevmoo** [comment]
Can you provide more details? An example? The error output?

**Comment by kevmoo** [comment]
Going to close this. Feel free to reply if you have more info...

**Comment by xiprox** [comment]
Hello,

I'm working with an API returning responses in the following format:
```json
{
    "status": "ok",
    "message": "Query successful.",
    "data": [
        {
            ...
        }
     ]
}
```
where the contents of `data` are different models for different requests. 

Coming from Android, it feels ideal to me to create a wrapper model like the following:
```dart
@JsonSerializable()
class Response<T> extends Object with _$ResponseSerializerMixin {
  Response(
    this.status,
    this.message,
    this.code,
    this.data,
  );

  String status;
  String message;
  String code;
  T data;

  // ...
}
```

However, I haven't been able to find a nice way for deserialization here.

I do the following as some sort of a workaround but it's very ugly as it takes the problem to higher level code:
```dart
factory Response.fromJson(
    Map<String, dynamic> json,
    ResponseDataDeserializerFunction<T> dataFromJson,
  ) {
    Response tempResponse = _$ResponseFromJson(json);
    Response<T> response = new Response(
      tempResponse.status,
      tempResponse.message,
      tempResponse.code,
      tempResponse.dataJson,
    );
    // As we have no idea how to do deserialization based on a generic alone,
    // we let callers of this function handle it and return an object of type T.
    response.data = dataFromJson(response.dataJson);
    return response;
}

// ...

typedef T ResponseDataGeneratorFunction<T>(Map<String, dynamic> json);

// Later in higher level:
// ...
return new Response<AccountData>.fromJson(json, (dataJson) {
   return new AccountData.fromJson(dataJson);
});
// ...
```

It would be wonderful if somehow generics could be supported. If not, and if you have a better approach on how to tackle this issue, I would absolutely love to learn about it.

**Comment by kevmoo** [comment]
I think we can do something here. Thanks for the details!

**Comment by kevmoo** [comment]
@xiang23 this will come in `v0.5.4` – which should be out today...
