### ISSUE TITLE
Support custom DateTime formats

### ISSUE THREAD

**Issue by westy92** [dart-lang/json_serializable#133]
I'd like to (un)serialize a DateTime in a custom format, such as:
```dart
 new DateFormat('M/d/yyyy');
```

Currently I get a runtime exception:
```
I/flutter (20794): FormatException: Invalid date format
I/flutter (20794): 04/10/2015
```

**Comment by westy92** [comment]
Is it possible using a similar method to [this](https://github.com/dart-lang/json_serializable/blob/master/json_serializable/tool/build.dart#L84-L85)?

**Comment by thosakwe** [comment]
I think that the `TypeHelper` functionality could potentially solve this for you. I'm not 100% sure how to use it, but it seems like once it's documented it'll be a possibility.

**Comment by kevmoo** [comment]
This will be easily solved with https://github.com/dart-lang/json_serializable/pull/146

**Comment by kevmoo** [comment]
See here for how you can get this done w/out creating a custom `TypeHelper`.

https://github.com/dart-lang/json_serializable/blob/bb96ddc0c241d07879d06f2209a210d2e73df31b/json_serializable/test/test_files/json_test_example.dart#L125-L151

Will be published soon!

**Comment by westy92** [comment]
Thanks! I got this to work. Leaving a `DateTime` with a custom format example for others:

```dart
@JsonSerializable()
class Test extends Object with _$TestSerializerMixin {

  @JsonKey(fromJson: _fromJson, toJson: _toJson)
  final DateTime date;

  Test({
    this.date,
  });

  factory Test.fromJson(Map<String, dynamic> json) => _$TestFromJson(json);
}

final _dateFormatter = new DateFormat('M/d/yyyy');
DateTime _fromJson(String date) => _dateFormatter.parse(date);
String _toJson(DateTime date) => _dateFormatter.format(date);
```

**Comment by kevmoo** [comment]
So glad!

**Comment by tulioccalazans** [comment]
Ah, its gotta be a static member.

```
static DateTime _fromJson(String date) => _dateFormatter.parse(date);
static String _toJson(DateTime date) => _dateFormatter.format(date);
```

**Comment by fluttercorner** [comment]
[How to Display Current DateTime in Flutter](https://fluttercorner.com/how-to-display-current-datetime-in-flutter/)

**Comment by Sunbreak** [comment]
```dart
@JsonSerializable()
class TestItem {
  @JsonKey(fromJson: DateTimeHelper.toIso8601Json, toJson: DateTimeHelper.toIso8601Json)
  String createTime;

  TestItem(this.createTime);

  factory TestItem.fromJson(Map<String, dynamic> json) => _$TestItemFromJson(json);

  Map<String, dynamic> toJson() => _$TestItemToJson(this);
}

extension DateTimeHelper on DateTime {
  static DateTime fromIso8601Json(String json) => DateTime.parse(json);

  static String toIso8601Json(DateTime date) => date.toIso8601String();
}
```
