### ISSUE TITLE
Add casting support

### ISSUE THREAD

**Issue by ianldgs** [dart-lang/json_serializable#137]
I've integrated with a very bad API. Their JSON didn't have any types, it was all strings. It would be very usefull to have something like this:

```json
{
  "ugly": "true",
}
```

```dart
@JsonSerializable()
class Example {
  Example({this.pretty});

  @JsonKey(
    name: 'ugly',
    fromJson: (v) => v == 'true',
    toJson: (v) => v.toString(),
  )
  final bool pretty;
}
```

**Comment by ianldgs** [comment]
It might even solve #133

**Comment by kevmoo** [comment]
build_cli does this - https://github.com/kevmoo/build_cli/blob/1e24d4b78c6e7eaa5b3a8024cd182875c76c2e02/build_cli/test/src/peanut_example.dart#L61

**Comment by jmrboosties** [comment]
running into a similar issue. firebase stores a field like "created_at" as a datetime, but the generated file builds this:

```
..createdAt = json['created_at'] == null
          ? null
          : DateTime.parse(json['created_at'] as String)
```

which breaks the parsing. im gonna explore your build_cli lib but itd be nice to have a way to get around this within this lib if possible. thanks!

**Comment by kevmoo** [comment]
Far from done, but I have it bootstrapped - https://github.com/dart-lang/json_serializable/pull/146

**Comment by kevmoo** [comment]
Firebase is another problem. The values it returns are JSON-like, but do
include non-JSON values like blobs, dates, geo points, etc.

**Comment by jmrboosties** [comment]
thanks. yea, firebase's handling of date is a bit unusual. it looks like if i were able to flag the field as such, it could parse correctly if the generated file just simple did `createdAt = json['created_at']`. the error i receive states that the type mismatch is String != DateTime, which is the type of `createdAt`

**Comment by kevmoo** [comment]
RE firebase.

You could always use https://pub.dartlang.org/documentation/json_serializable/0.5.0/json_serializable/JsonSerializableGenerator/JsonSerializableGenerator.html – and put in your own TypeHelper for DateTime that's a no-op.

**Comment by jmrboosties** [comment]
thanks! ill have a look.

**Comment by kevmoo** [comment]
Can the map from Firebase support non-String keys? If so, we should fix
that...

**Comment by kevmoo** [comment]
What method are you calling where it returns Map<dynamic, dynamic>? What's
the stack trace?

**Comment by jmrboosties** [comment]
The stack trace is just what I posted before, nothing more unfortunately

```
I/flutter ( 5948): type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' where
I/flutter ( 5948):   _InternalLinkedHashMap is from dart:collection
I/flutter ( 5948):   Map is from dart:core
I/flutter ( 5948):   String is from dart:core
```

This is the code that triggers it:

```
_firestore = Firestore.instance;

return _firestore.collection('favorites').where('user_id', isEqualTo: uid).getDocuments()
				.then((querySnap) {
					querySnap.documents.forEach((document) {
						print(document.data);

						Map<String, dynamic> json = document.data; //casts, but if you put breaklines through this its that _InternalLinkedHashMap<dynamic, dynamic> type
						Album album = new Album.fromJson(json['favorite_albums'][0]); //Throws the type exception
					});
				})
				.catchError((error) {
					print(error);
				});
```

The actual aim here is to just loop through the results and add them to a list, but I'm just manually grabbing object 0 here as part of my debugging, so forgive the loop for seemingly no reason haha.

**Comment by kevmoo** [comment]
Ah! You're using the Flutter firebase SDK. I was looking at the source for
https://github.com/firebase/firebase-dart

You should file an issue https://github.com/flutter/flutter/issues –
mention reference this discussion!

**Comment by jmrboosties** [comment]
ill do that, thanks!

**Comment by jmrboosties** [comment]
I'm interested in trying those to/from json functions you can declare in the JsonKey. I see it committed to master, but you haven't made a release for it yet. I could pull down the source code of course but TBH I'm not sure how I would integrate that with my project if I did. Also, as a suggestion it might be nice to have a class-wide option for those to/from json functions, similar to how in Gson you can declare a custom deserializer for an entire class.

Thanks again

**Comment by ianldgs** [comment]
Thats awesome @kevmoo! Waiting for the release!!

**Comment by kevmoo** [comment]
@jmrboosties – release is coming soon

For whole classes, just add a toJson method and a fromJson ctor – it should work!
