### ISSUE TITLE
flutter packages pub run build_runner build fail

### ISSUE THREAD

**Issue by CaiJingLong** [dart-lang/json_serializable#139]
#0      _Loader._initialBuildCleanup (package:build_runner/src/generate/build_definition.dart:422:9)
<asynchronous suspension>
#1      _Loader.prepareWorkspace.<anonymous closure> (package:build_runner/src/generate/build_definition.dart:130:17)
#2      logTimedAsync (package:build_runner/src/logging/logging.dart:26:30)
<asynchronous suspension>
#3      _Loader.prepareWorkspace (package:build_runner/src/generate/build_definition.dart:127:13)
<asynchronous suspension>
#4      BuildDefinition.prepareWorkspace (package:build_runner/src/generate/build_definition.dart:65:12)
#5      WatchImpl._run.<anonymous closure> (package:build_runner/src/generate/watch_impl.dart:264:48)
<asynchronous suspension>
#6      WatchImpl._run (package:build_runner/src/generate/watch_impl.dart:283:6)
#7      new WatchImpl (package:build_runner/src/generate/watch_impl.dart:160:9)
#8      runWatch (package:build_runner/src/generate/watch_impl.dart:115:9)
#9      watch (package:build_runner/src/generate/watch_impl.dart:94:7)
<asynchronous suspension>
#10     watch (package:build_runner/src/generate/build.dart:124:5)
#11     _WatchCommand.run (package:build_runner/src/entrypoint/options.dart:298:25)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#13     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#14     new Future.sync (dart:async/future.dart:224)
#15     CommandRunner.run (package:args/command_runner.dart:109:11)
#16     run (package:build_runner/src/entrypoint/run.dart:15:24)
<asynchronous suspension>
#17     main (file:///Users/cjl/IdeaProjects/flutter/flutter-wanandroid/.dart_tool/build/entrypoint/build.dart:12:22)
<asynchronous suspension>
#18     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
pub finished with exit code 1

---------------
When I run the 'flutter packages pub run build_runner watch' or 'flutter packages pub run build_runner build', I get the error with my commend line.

----
I use the json_serializable: "^0.5.0"

**Comment by CaiJingLong** [comment]
I hava 2 mac ,
In my comp no have the problem,but I get the log in my house.

**Comment by kevmoo** [comment]
Going to close this. Feel free to reply if you have more info...

**Comment by zirinisp** [comment]
I was getting a similar error. After "pub upgrade", I am not getting it anymore
