### ISSUE TITLE
Git warnings about "LF" being replaced by "CRLF" on windows 

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/json_serializable#143]
After building when commiting files I consistently get these warnings for each generated file. This might be a `source_gen` issue?

```
warning: LF will be replaced by CRLF in lib/some_path.g.dart.
The file will have its original line endings in your working directory.
```

**Comment by kevmoo** [comment]
Closing this out. This should be solved at the source_gen level, if anywhere.

`dartfmt` runs over the code anyway – so I'm wondering if the only place this is happening is with String literals with embedded newlines?
