### ISSUE TITLE
More than one field has the JSON key `item`.

### ISSUE THREAD

**Issue by fatherchill** [dart-lang/json_serializable#165]
Unsure if this is a new feature or just a case of not understanding how to use it correctly.

I use xml2json to convert an xml into Google Data json. A 'section' has one or more 'item' children. If there is only one, it becomes an Object property. If there are multiple, an Array.

Currently I have:   @JsonKey(name: "item", nullable: true)
  final List<Item> items;

But it throws an error when encountering an item Object.

Is there any way to ensure that a single Item Object will get serialized into a <List>, or is there another way of handling this?

**Comment by kevmoo** [comment]
We recently added `fromJson`, `toJson` properties to `JsonKey` that let you provide methods to handle conversion yourself. You could detect if the value is a list or a single value and populate the property accordingly.

**Comment by fatherchill** [comment]
Thanks, I appreciate the clarification. I know this isn't a help forum, but for the life of me I can't figure out what syntax I need to use with the fromJson and there isn't really any documentation for those functions. You mind helping me understand how I can use fromJson to handle either a list or a single item in the following case?

 ```
 @JsonKey(name: 'book',)
  final List<Book> books;

  BooksContainer(
      this.books,
      );
```

**Comment by fatherchill** [comment]
Thanks, I appreciate the clarification. I know this isn't a help forum, but for the life of me I can't figure out what syntax I need to use with the fromJson and there isn't really any documentation for those functions. You mind helping me understand how I can use fromJson to handle either a list or a single item in the following case?

 ```
 @JsonKey(name: 'book',)
  final List<Book> books;

  BooksContainer(
      this.books,
      );
```

**Comment by kevmoo** [comment]
Something like 

```dart
List<Book> _decodeBooks(Object input) {
  // your code here
}

class MyClass {
  @JsonKey(name: 'book', fromJson: _decodeBooks)
  final List<Book> books;
}
```

**Comment by fatherchill** [comment]
Thanks -- it took a bit for me to understand, but it's working now!

**Comment by kevmoo** [comment]
Awesome!

**Comment by fatherchill** [comment]
I don't want to hastily open another issue. Yet after implementing fromJSON, debugging and running from Android Studio works fine, but release builds give a type mismatch error in my fromJSON method.

>  06-16 10:23:59.541  6695  6712 E flutter : [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
> 06-16 10:23:59.541  6695  6712 E flutter : type '_OneByteString' is not a subtype of type 'int' of 'index'
> 06-16 10:23:59.541  6695  6712 E flutter : #0      _GrowableList.[] (dart:core/runtime/libgrowable_array.dart:0)

Is there a problem in my code or is this an actual issue?

The offending method is below and here is the repository: https://github.com/fatherchill/world_liturgy_app/tree/CalendarAndCollects

```
List<dynamic> _decodePrayerBookorService(itemOrList){
//  debugPrint(itemOrList);
  print('begin decode Prayerbook or Service');

  List<dynamic> list = [];
  if (itemOrList == null){
    return null;
  }
  if (itemOrList.runtimeType.toString() == 'List<dynamic>'){
    list = itemOrList;
  }else{
    list.add(itemOrList);
  }

  print(list.toString().substring(0,20));

  if (list.first['service'] != null){
    return list.map((e) =>
    e == null ? null : new PrayerBook.fromJson(e as Map<String, dynamic>))
        ?.toList();
  }else if (list.first['section'] != null){
    return list.map((e) =>
    e == null ? null : new Service.fromJson(e as Map<String, dynamic>))
        ?.toList();
  }else{
    return null;
  }
```

}

**Comment by kevmoo** [comment]
```dart
List<dynamic> list = [];
  if (itemOrList == null){
    return null;
  }
  if (itemOrList.runtimeType.toString() == 'List<dynamic>'){
    list = itemOrList;
  }else{
    list.add(itemOrList);
  }
```

Don't do that!

```dart
  if (itemOrList == null){
    return null;
  }
  List list;
  if (itemOrList.runtimeType.toString() == 'List<dynamic>'){
    list = itemOrList;
  }else{
    list = [itemOrList];
  }
```

Not sure if that'll help...but it's better...

**Comment by fatherchill** [comment]
Thanks. I appreciate the coding pointers though that wasn't the solution.

The problem was that in the release build runtimeType returns 
'_GrowableList<dynamic>' while debug builds return 'List<dynamic>'.

**Comment by a-wallen** [comment]
For anyone else coming to this issue due to: `More than one field has the JSON key for name <name>`, you might be in this situation

`
class MyClass 
{
  SomeType A;

  @JsonKey(name: 'A')
  SomeType B;
}
`

It is possible if you are trying to rename a field on deserialization. You can solve it like this:

`
class MyClass 
{
  @JsonKey(ignore: true)
  SomeType A;

  @JsonKey(name: 'A')
  SomeType B;
}
`
