### ISSUE TITLE
JsonKey: Add an option to exclude a field from `toJson`

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/json_serializable#178]
Even if it's available in the constructor...

**Comment by mikes222** [comment]
I would like to have an enhancement of the `@JsonKey(ignore: true)` feature. Something to be able to specify a property to being ignored for incoming/outgoing like so: 
<code>
    @JsonKey(ignore: true) // already existing, ignores a property completely
    @JsonKey(ignoreFromJson: true) // new, ignores a property in the fromJson() method
    @JsonKey(ignoreToJson: true) // new, ignores a property in the toJson() method
</code>

**Comment by kevmoo** [comment]
This already exists - https://github.com/dart-lang/json_serializable/pull/118

Uh...I'm must be loosing it...

@mikes222 – feel free to add your other ideas as separate issues
