### ISSUE TITLE
Support an option to not allow explicit null values for nullable fields.

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/json_serializable#183]
See [InputSet](https://github.com/dart-lang/build/blob/master/build_config/lib/src/input_set.dart) as an example. Both of its fields are allowed to be null, but we don't really want users to be able to specify them as null explicitly in yaml. For instance, this should give an error:

```yaml
targets:
  $default:
    sources:
      include:
```

`include:` there isn't treated any differently than if it didn't exist at all, and should probably be an error.

**Comment by kevmoo** [comment]
This is a weird angle on `required`, but orthogonal. Something like `disallowNull` or `mustContainValue`?

It'd be pretty easy to roll into `$checkKeys`
