### ISSUE TITLE
Add an option to explicitly call toJson when generating serialization code

### ISSUE THREAD

**Issue by jmrboosties** [dart-lang/json_serializable#192]
So rummaging through some older issues, I found that the expected way to handle an structure like:

```
User
---List<Favorites>
```
Is to do something like this:

`Map<String, dynamic> jsonObject = json.decode(json.encode(user)); //json is from dart:convert`

Instead of the normal user.toJson which works with objects without other nested objects inside of  them. This isn't a huge deal, but it just makes the code look a little weird. If there's a better way to do this please let me know. Thanks!

**Comment by kevmoo** [comment]
Right now we DON'T call `toJson` on nested objects when we write `toJson` – because this is done by `jsonEncode` for us.

We could certainly add an option to explicitly call `toJson` in these cases, though.

**Comment by jmrboosties** [comment]
Ok so by design (right now) toJson should only work with flat structures. Yea a way with an annotation or something to have it go through each layer (how Gson works) would be cool. Thanks!

**Comment by kevmoo** [comment]
> toJson should only work with flat structures

What do you mean here?
