### ISSUE TITLE
Add ability to reference values inside nested objects

### ISSUE THREAD

**Issue by jmrboosties** [dart-lang/json_serializable#196]
I ran into this problem when trying to parse some JSON with unnecessary nesting (for my purposes) in it's structure:

```
"name": "document collection",
"id": 123
"documents": {
	"href": "https://urltodocuments",
	"total": 3
}
```

I'd like to have an object that looks like this:

```
class DocCollection {

    String name;
    int id;
    int totalDocuments;
    String documentsUrl

}
```

Initially, I tried this:

```
@JsonKey(name: 'documents, fromJson: _getTotalDocuments)
int totalDocuments;

@JsonKey(name: 'documents', fromJson: _getDocumentsUrl)
String documentsUrl;

//Outside of class
int _getTrackCount(Map<String, dynamic> input) {
	return input['total'];
}

String _getTracksUrl(Map<String, dynamic> input) {
	return input['href'];
}
```

However the package doesn't allow you to tag two variables with the same key name. This would have been a work around anyway, what I'd really like to do is something like this:

```
@JsonKey(name: 'documents.total)
int totalDocuments;

@JsonKey(name: 'documents.href')
String documentsUrl;
```

Which would achieve the same effect. Let me know if this is something that can be added. I know I've been making a lot of requests, I really appreciate you guys listening and responding!

**Comment by kevmoo** [comment]
Interesting idea! Pull requests welcome!

**Comment by jmrboosties** [comment]
I'm new to dart but yea I'll give it a try!

**Comment by spagni** [comment]
Hey any news on this issue? I'd really love this solution. I need to reference values inside nested objects in my json.

Can I help in some way?

**Comment by kevmoo** [comment]
The most simple way to do it, take a look at this

https://github.com/dart-lang/json_serializable/blob/ab724f9e38e98105626e86565e95f9dd6b19a2e4/example/lib/example.dart#L33-L54

You could simply add 

```dart
int get itemCount => item?.count;
```

This of course means you'd have to create a class for the nested object – is that a problem?

**Comment by spagni** [comment]
@kevmoo  Hey Kevin, I'm having a hard time trying to understand what you meant. Let me show you what I'd like to do.

I'm receiving this json
```
{
    "Code": 200,
    "Message": "OK",
    "ResponseObject": {
        "Token": "..token..",
        "Language": "en-US"
    }
}
```
And in my class I'm annotating the token property with @JsonKey() name as 'ResponseObject', that way I can use the fromJson function to retrieve the token value from the json. 
That works perfectly fine, the problem comes when I try to deserialize the language property. I can't apply the same solution because I can't repeat the @JsonKey() 'ResponseObject' name.
I hope I'm making myself clear. 
```
import 'dataContracts/base_response.dart';
import 'package:json_annotation/json_annotation.dart';
part 'login_response.g.dart';

@JsonSerializable()
class LogInResponse extends BaseResponse with _$LogInResponseSerializerMixin {

  @JsonKey(name: 'ResponseObject', fromJson: _getResponseObject)
  String token;
  //Here I'm having trouble, because I can't repeat the ResponseObject name on @JsonKey()
  String language;

  LogInResponse(int code, String message) : super(code, message);

  factory LogInResponse.fromJson(Map<String, dynamic> json) => _$LogInResponseFromJson(json);
}

String _getResponseObject(Map<String, dynamic> json) {
  return json['Token'];
}
```

I really appreciate your help Kevin. Thank you!

**Comment by spagni** [comment]
@kevmoo I definetly can do that but I'll be loosing the abstraction I'm seeking. 

See, ReseponseObject will carry any amount of diferent objects. In this case it carries a Token and Language. But that is only one of the many possible cases.

**Comment by kevmoo** [comment]
Or you could use toJson/fromJson on the `responseObject` field and then detect the type of object and serialize as appropriate...
