### ISSUE TITLE
flutter_test from sdk is incompatible with json_serializable >=0.5.3.

### ISSUE THREAD

**Issue by wooldridgetm** [dart-lang/json_serializable#241]
After updating my pubspec.yaml with my dependencies (denoted below), the flutter tool is giving me this error when I try **flutter packages get**

_Because every version of flutter_test from sdk depends on test 0.12.37 which depends on analyzer >=0.26.4 <0.32.0, every version of flutter_test from sdk requires analyzer >=0.26.4 <0.32.0.
And because json_serializable >=0.5.3 depends on analyzer ^0.32.0,_ **flutter_test from sdk is incompatible with json_serializable >=0.5.3**.
_So, because jam2018 depends on both json_serializable ^0.5.4 and flutter_test any from sdk,_ **version solving failed**.
**pub get failed** (1)

<img width="423" alt="screen shot 2018-06-19 at 2 29 35 pm" src="https://user-images.githubusercontent.com/13317009/41616929-3ac13e36-73cd-11e8-95d8-518c78b89d60.png">

is there any way around this issue?

**Comment by kevmoo** [comment]
Which version of Flutter are you on? Did you upgrade to the latest beta (today)?

**Comment by wooldridgetm** [comment]
Yes, I'm pretty sure I checked my latest version of Flutter was up-to-date, but to be sure, I checked again.  Flutter Doctor reported no issues, but I get a slightly different error this time in the console after running _flutter packages upgrade_.

**Flutter Version info**

_Flutter 0.5.1 • channel beta • https://github.com/flutter/flutter.git_
_Framework • revision c7ea3ca377 (3 weeks ago) • 2018-05-29 21:07:33 +0200_
_Engine • revision 1ed25ca7b7_
_Tools • Dart 2.0.0-dev.58.0.flutter-f981f09760_

<img width="690" alt="flutter upgrade console output" src="https://user-images.githubusercontent.com/13317009/41681007-547be11c-74a1-11e8-9350-9697635504b2.png">

**Comment by wooldridgetm** [comment]
**Error Message from 'flutter packages upgrade'**

_Because every version of flutter_test from sdk depends on analyzer 0.31.2-alpha.2 and json_serializable >=0.5.3 depends on analyzer ^0.32.0, flutter_test from sdk is incompatible with json_serializable >=0.5.3._

_So, because jam2018 depends on both json_serializable ^0.5.4 and flutter_test any from sdk, version solving failed._

_pub get failed (1)_

<img width="890" alt="screen shot 2018-06-20 at 4 01 09 pm" src="https://user-images.githubusercontent.com/13317009/41681643-3464655a-74a3-11e8-8ef3-014f38ab9249.png">

**Comment by kevmoo** [comment]
Yup. `flutter_test` needs to be updated to support the latest analyzer. I'd file a bug on the flutter repo...reference this issue...

**Comment by pcqpcq** [comment]
just a workaround for me:

remove `flutter_test`, and use `build_runner: "^0.8.10"` for now.

and wait for flutter_test to be updated to support the latest analyzer.

```yaml

dev_dependencies:
  # flutter_test:   # <-- remove this for now.
  #   sdk: flutter
  
  build_runner: "^0.8.10"  # <-- use this for now.
  json_serializable: "^0.5.8"
```

**Comment by kevmoo** [comment]
The suggestion from @pcqpcq is a good one.

**Comment by RomanSoviak** [comment]
Downgrade version of JSON_serializable
