### ISSUE TITLE
Publish new version on pub

### ISSUE THREAD

**Issue by sir-boformer** [dart-lang/json_serializable#259]

**Comment by kevmoo** [comment]
Waiting on updates to source_gen first.

Any specific feature you're waiting on, @sir-boformer ?

**Comment by sir-boformer** [comment]
The improved enum serialization

**Comment by kevmoo** [comment]
> The improved enum serialization

It is nice, isn't it!

Hopefully this coming week. Thanks for your patience.

**Comment by sir-boformer** [comment]
It's super nice! Compared to other programming languages, json serialization in Dart/Flutter still feels kind of clunky, but you made the best out of it!

**Comment by kevmoo** [comment]
Feel free to email me (github name)@google – I'd love to know how we could
make it better!

**Comment by sir-boformer** [comment]
Thanks for the update. The new enum serialization and removal of mixins really improved the experience!

**Comment by kevmoo** [comment]
So happy to hear that!
