### ISSUE TITLE
How to serialize the mongodb '_id' ?

### ISSUE THREAD

**Issue by Yaxian** [dart-lang/json_serializable#261]
Hi,
I have a problem to serialize mongodb document, because of the `_id` field.
For example,
`account` collection is
```
{ _id: 1, name: 'test'}
```
`account.dart` file is like below:

```
import 'package:json_annotation/json_annotation.dart';
part 'account.g.dart';

class Account extends Object with _$AccountSerializerMixin {
  // final String id;
  @JsonKey(name: '_id')
  String _id;
  String name;
  

  Account(
      this._id,
      this.name,
);
  factory Account.fromJson(Map<String, dynamic> json) =>
      _$AccountFromJson(json);
}

```
it will fail to run `flutter packages pub run build_runner watch`. Any idea about the problem?

**Comment by Yaxian** [comment]
Oh, I resolved it:

```
@JsonKey(name: '_id')
String id;

 Account(
      this.id,
      this.name,
)
```

**Comment by AdityaBirangal** [comment]
You can replace `'_id'` with `'id'` once you got JSON Response String. Then serialize it.

Model Class :

    @JsonSerializable(explicitToJson: true)
    class PersonModel{
      int id;
      String name;
    
      PersonModel(this.id,this.name);
    
      factory PersonModel.fromJson(Map<String, dynamic> json) => _$PersonModel FromJson(json);
    
      Map<String, dynamic> toJson() => _$PersonModelToJson(this);
    }


Replace : 

    String responseString = response.body
    String newResponseString = responseString.replaceAll('_id', 'id');
    PersonModel personModel = PersonModel.fromJson(jsonDecode(newResponseString));

Now you can use `personModel.id` to access `_id` in frontend.

    
https://stackoverflow.com/questions/62280070/how-to-make-a-public-property-even-with-underscore-in-dart/73059455#73059455
