### ISSUE TITLE
Support for quiver's Optional

### ISSUE THREAD

**Issue by sir-boformer** [dart-lang/json_serializable#268]
It would be nice if there was a simple way to serialize and deserialize properties wrapped in an `Optional`:
https://github.com/google/quiver-dart/blob/master/lib/src/core/optional.dart

**Comment by kevmoo** [comment]
You could create your own `TypeHelper` or use the fromJson/toJson annotations on a field.

I don't want to add a dependency on quiver to this package, although it'd be easy to create a supplementary package to support those.
