### ISSUE TITLE
User vs Generated code cleanup

### ISSUE THREAD

**Issue by cbazza** [dart-lang/json_serializable#270]
This is more of a question than anything else.

In your **example.dart** file you have:
```dart
import 'package:json_annotation/json_annotation.dart';

part 'example.g.dart';

@JsonSerializable(nullable: false)
class Person {
  final String firstName;
  final String lastName;
  final DateTime dateOfBirth;
  Person({this.firstName, this.lastName, this.dateOfBirth});
  factory Person.fromJson(Map<String, dynamic> json) => _$PersonFromJson(json);
  Map<String, dynamic> toJson() => _$PersonToJson(this);
}
```
 Why don't you put those last 2 methods in the generated part so the user code is cleaner?
```dart
import 'package:json_annotation/json_annotation.dart';

part 'example.g.dart';

@JsonSerializable(nullable: false)
class Person {
  final String firstName;
  final String lastName;
  final DateTime dateOfBirth;
  Person({this.firstName, this.lastName, this.dateOfBirth});
}
```

**Comment by kevmoo** [comment]
We really want partial classes here - https://github.com/dart-lang/sdk/issues/8547

I'm generating the private, top-level methods but there is no way to "glue" them into the class from a part file.

The mixin got us the `toJson` method, but the user still had to wire up the `factor` constructor.  It also meant we had to create abstract members for all of the fields in the `toJson` mixin.

We felt it was better to have everything be a static function and one mixin.

Make sense?

**Comment by cbazza** [comment]
Yes, got it, thanks.

**Comment by Meai1** [comment]
it would also be solved if code could be generated into an existing file though

**Comment by kevmoo** [comment]
> Partial Classes or Extension Functions

Both are still being discussed, @cbazza – partial classes in particular would help a lot

> it would also be solved if code could be generated into an existing file though

We explicitly avoid that @Meai1 – sooo many ways for that to fail. It also makes automating dependency checking, etc very difficult.

**Comment by vinicioslc** [comment]
I liked so much the idea of use partial classes for code cleanup and arrangement. *- *
