### ISSUE TITLE
Documentations about sdk version constraints are outdated

### ISSUE THREAD

**Issue by kdy1** [dart-lang/json_serializable#271]
- [ ] https://github.com/dart-lang/json_serializable/blob/9af62981ec190e2e3e4c82195ece440cc15699c4/example/README.md

I switched my flutter channel to dev, but I got

```

Running "flutter packages get" in chess.dart...
The current Dart SDK version is 2.0.0-dev.63.0.flutter-4c9689c1d2.

Because json_serializable 1.0.0 requires SDK version >=2.0.0-dev.65 <3.0.0 and no versions of json_serializable match >1.0.0 <2.0.0, json_serializable ^1.0.0 is forbidden.
So, because chess depends on json_serializable ^1.0.0, version solving failed.
pub get failed (1)

```

**Comment by adriancmurray** [comment]
I'm getting the same thing. The master channel seems to work for this package but using that channel has unexpected issues for my app.

**Comment by jaggerwang** [comment]
I'm came into the same problem. Why require the newest master channel, it's so unstable!

**Comment by kevmoo** [comment]
Sorry about that. This is blocked on Flutter releasing `0.5.8` which will have a Dart SDK >= -dev.65

**Comment by kevmoo** [comment]
See the example repo at https://github.com/dart-lang/json_serializable/blob/b6933999a2f73f4b5bd4de7820c63b52847c63dd/example/README.md to  see a version that should work with Flutter now...

**Comment by MaskyS** [comment]
Got this same issue. Disabling flutter_test  and using   `json_serializable: ^0.5.8` works as a hack.

**Comment by readytopark** [comment]
@MaskyS Can you please share the full pubspec that's working for you?

**Comment by hahn** [comment]
@readytopark use old stable release

```
dev_dependencies:
#  flutter_test:
#    sdk: flutter

  build_runner: "^0.8.10"
  json_serializable: "^0.5.8"
```
