### ISSUE TITLE
Handle different types for a json field

### ISSUE THREAD

**Issue by mjohnsullivan** [dart-lang/json_serializable#277]
Picture a situation where one of the fields returns a variable type: it typically returns a string, but occasionally returns 0 if there's not content (real world example). So you end up with having to deal with either getting and int or string:

The following doesn't work:

```dart
@JsonKey(fromJson: _descFromValue)
final String desc;

String _descFromValue(dynamic descValue) {
  if (descValue is int) return '';
  return descValue as String;
}
```
Problem is the generated code has:

```dart
desc: _descFromValue(json['desc'] as String);
```

It throws a type error with desc is an int.

It would be great if it were possible to manipulate the type before the cast happens.

**Comment by kevmoo** [comment]
I just did this:

```dart
@JsonSerializable(createToJson: false)
class Matt {
  @JsonKey(fromJson: _descFromValue)
  final String desc;

  Matt(this.desc);
}

String _descFromValue(dynamic descValue) {
  if (descValue is int) return '';
  return descValue as String;
}
```

and got this generated
```dart

Matt _$MattFromJson(Map<String, dynamic> json) {
  return Matt(json['desc'] == null ? null : _descFromValue(json['desc']));
}
```

This is with json_serializable @ 1.01

**Comment by kevmoo** [comment]
Closing this out, @mjohnsullivan – let me know if you think this is more than just version lag w/ Flutter
