### ISSUE TITLE
Request for adding support to generate the code in a separate folder to keep the main code directory clean

### ISSUE THREAD

**Issue by mayur-novus** [dart-lang/json_serializable#306]
Hi.
This is really a feature request. Can you modify this awesome library to accept some the folder name as part of the `part 'somefile.g.dart'` ? Example: `part './generated/somefile.g.dart'` ? This would really help to keep our main source files directory clean.

**Comment by mayur-novus** [comment]
This should be easy with relative paths.

I created a folder - `generated` and moved all the `*.g.dart` files to this folder.
Then, I had to change the line `part of 'somefile.dart'` to `part of '../somefile.dart'`
And inside the source files, the line that says `part 'somefile.g.dart'` to `part './generated/somefile.g.dart'`

**Comment by mayur-novus** [comment]
And it will be much better if you can add the project name from `pubspec.yaml` and use full paths like:
`part 'package:project_name/folder_name/somefile.g.dart'`
And 
`part of 'package:project_name/some_other_folder/somefile.dart'`;

This would be much useful when refactoring / moving the files using Android Studio - It will automatically refactor the paths as well. :smiley:

**Comment by kevmoo** [comment]
Our code generation model is very optimized around emitting generated files next to their source files.

RE using 'package:' URIs for parts, I'd argue this is a bug in our editing tools that they don't handle moves better.

**Comment by mayur-novus** [comment]
It is annoying to have more than 30 *.g.dart files in my source code directory and is not easy to maintain. 
Moreover, I would argue too in favor of efficiency of the editing tools: Android studio does refactor the files automatically to have correct `package:` paths when files are moved around. I have had no issues in refactoring as it is an IntelliJ based IDE, it is simply the best.

**Comment by kevmoo** [comment]
@jakemac53 @natebosch – thoughts here?

**Comment by bagintz** [comment]
What about an annotation in the source file that says where to put the part?

**Comment by natebosch** [comment]
> What about an annotation in the source file that says where to put the part?

See the linked discussion - we need to know statically, without reading any of the input files, what outputs can exist and where they'd come from. This is what enables to lazily trigger builds.

**Comment by pinguluk** [comment]
Any update regarding this?

**Comment by jakemac53** [comment]
See https://github.com/dart-lang/source_gen/tree/master/source_gen#generating-files-in-different-directories

**Comment by MikeAndrson** [comment]
Any update on this?

**Comment by makrasnov100** [comment]
@realshovanshah @MikeAndrson and anyone else still having issues
Making a `build.yaml` file with the following contents does work great for me when using the latest `json_serializable` (6.2.0)

Note: my models which make use of the generator all reside within the `classes` directory but the generated files are created in the `generated` directory.

```yaml
//build.yaml
targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/classes/{{}}.dart': 'lib/generated/{{}}.g.dart'
```

**Comment by docaohuynh** [comment]
For who use with freezed package
[#633](https://github.com/rrousselGit/freezed/issues/633)

**Comment by BlueDev5** [comment]
> @realshovanshah @MikeAndrson and anyone else still having issues Making a `build.yaml` file with the following contents does work great for me when using the latest `json_serializable` (6.2.0)
> 
> Note: my models which make use of the generator all reside within the `classes` directory but the generated files are created in the `generated` directory.
> 
> ```yaml
> //build.yaml
> targets:
>   $default:
>     builders:
>       source_gen:combining_builder:
>         options:
>           build_extensions:
>             '^lib/classes/{{}}.dart': 'lib/generated/{{}}.g.dart'
> ```

I can't get it to work, I created a build.yaml in the root of the project and pasted the code you wrote. For starters, it gives an error on the first line of the file. And then when running build_runner it warns saying the properties set in the build.yaml will be ignored. And it doesn't generate anything.

**Comment by cedvdb** [comment]
Is it possible to generate in the same file ?

**Comment by kevmoo** [comment]
@cedvdb – nope. We want code generation to be "pure". Never mixing user-written and machine-written code
