### ISSUE TITLE
Support class-level annotation for defining custom type helpers

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/json_serializable#308]
See https://github.com/dart-lang/json_serializable/issues/202

Right now, there are two ways to extend decode/encode:

1. Provide toJson/fromJson on each field via `JsonKey`
    - requires re-specifying for every field referencing a type
    - does not take advantage of Iterable/Map support for decomposing collections
2. Create a custom `TypeHelper`
    - requires a bunch of `build.yaml` ceremony
    - cannot support class type parameters

```dart
@JsonSerializable(typeHelpers: {Customer: '_customer', 'T': '_genericHelper'})
class SomeClass<T> {
  List<T> items;
  Set<Customer> targetCustomers;
  Customer primaryCustomer;

  static Map<String, dynamic> _customerToJson(Customer customer) => null;
  static Customer _customerFromJson(Object json) => null;
}

T _genericHelperFromJson<T>(Object json) => null;
Object _genericHelperToJson<T>(T object) => null;

class Customer {
  // some stuff
}
```

**Comment by kevmoo** [comment]
@jakemac53 @natebosch – thoughts on this approach?

**Comment by jakemac53** [comment]
Not super sold on the magic stuff with the names, but absolutely sold on the general idea of providing annotation based type helpers that don't require a custom builder.

I never use the custom type helpers any more and copy the fromJson/toJson stuff all over because it is just a lot easier to do.

**Comment by kevmoo** [comment]
> Not super sold on the magic stuff with the names

I was trying to avoid making folks having to specify things twice. It'll be super easy to discovery and scream about if they name things wrong.

The "fromJson/toJson stuff" supports the field type, so it doesn't let you use the `List` support from JsonSerializable and then just write a helper for `T` in the `List<T>` case.

**Comment by jakemac53** [comment]
> I was trying to avoid making folks having to specify things twice. It'll be super easy to discovery and scream about if they name things wrong.

Ya, we could require a class that implements some interface too though, and then you can reference the type so it is less magic and you get IDE help. It could also help you in terms of knowing what api you are supposed to implement etc.

> The "fromJson/toJson stuff" supports the field type, so it doesn't let you use the List support from JsonSerializable and then just write a helper for T in the List<T> case.

Ya for sure - I am all to familiar with the use case haha

**Comment by natebosch** [comment]
I have some concerns:

- I don't think that moving the config from `@JsonKey` to the class level `@JsonSerializable` buys enough to pay for the increased complexity in documentation/discovery/implementation. How many classes use the same type helper multiple times in a class? It's a pretty small amount of boilerplate to reference the helpers in each field of that type.
- I don't have strong opinions on the magic with naming other than that it's now how we're doing it today with `@JsonKey` and I don't like having multiple ways to do things.
- I don't understand how the generics stuff helps here. I read through the linked issue and still don't quite understand what the problem is with specifying this in `@JsonKey`. If it is something that works in`@JsonSerializable` but not `@JsonKey` then that's yet another subtle thing to keep in mind and extra complexity in discovery and documentation.

I _do_ like being able to specify a type helper and have some the built in help with deserializing to collections instead of needing to create both versions of the helper yourself. Is there any way we can roll out support for that using the existing `@JsonKey` mechanism?

Can we chat about this in person in a few days?

**Comment by kevmoo** [comment]
Yeah, let's chat when I'm back (Friday...)

**Comment by kevmoo** [comment]
How 'bout this.

Unlike the JsonKey model, it actually plugs into the existing Map/List/Set support. Also, annotating with the actual converter is SUPER nice.

```dart
@JsonSerializable()
// referencing a top-level field should work
@_instance
// referencing via a const constructor should work
@_BigIntStringConverter()
@_NumberSillyConverter.instance
class JsonConverterTestClass {
  Duration duration;
  List<Duration> durationList;

  BigInt bigInt;
  Map<String, BigInt> bigIntMap;

  NumberSilly numberSilly;
  Set<NumberSilly> numberSillySet;
}

class NumberSilly {
  final int value;
  NumberSilly(this.value);
}

class _NumberSillyConverter implements JsonConverter<NumberSilly, int> {
  static const instance = const _NumberSillyConverter();

  const _NumberSillyConverter();

  @override
  NumberSilly fromJson(int json) => json == null ? null : NumberSilly(json);

  @override
  int toJson(NumberSilly object) => object?.value;
}

class _BigIntStringConverter implements JsonConverter<BigInt, String> {
  const _BigIntStringConverter();

  @override
  BigInt fromJson(String json) => json == null ? null : BigInt.parse(json);

  @override
  String toJson(BigInt object) => object?.toString();
}

const _instance = _DurationMillisecondConverter();

class _DurationMillisecondConverter implements JsonConverter<Duration, int> {
  const _DurationMillisecondConverter();

  @override
  Duration fromJson(int json) =>
      json == null ? null : Duration(milliseconds: json);

  @override
  int toJson(Duration object) => object?.inMilliseconds;
}
```

yields

```dart
JsonConverterTestClass _$JsonConverterTestClassFromJson(
    Map<String, dynamic> json) {
  return JsonConverterTestClass()
    ..duration = _instance.fromJson(json['duration'] as int)
    ..durationList = (json['durationList'] as List)
        ?.map((e) => _instance.fromJson(e as int))
        ?.toList()
    ..bigInt = const _BigIntStringConverter().fromJson(json['bigInt'] as String)
    ..bigIntMap = (json['bigIntMap'] as Map<String, dynamic>)?.map((k, e) =>
        MapEntry(k, const _BigIntStringConverter().fromJson(e as String)))
    ..numberSilly =
        _NumberSillyConverter.instance.fromJson(json['numberSilly'] as int)
    ..numberSillySet = (json['numberSillySet'] as List)
        ?.map((e) => _NumberSillyConverter.instance.fromJson(e as int))
        ?.toSet();
}

Map<String, dynamic> _$JsonConverterTestClassToJson(
        JsonConverterTestClass instance) =>
    <String, dynamic>{
      'duration': _instance.toJson(instance.duration),
      'durationList':
          instance.durationList?.map((e) => _instance.toJson(e))?.toList(),
      'bigInt': const _BigIntStringConverter().toJson(instance.bigInt),
      'bigIntMap': instance.bigIntMap?.map(
          (k, e) => MapEntry(k, const _BigIntStringConverter().toJson(e))),
      'numberSilly':
          _NumberSillyConverter.instance.toJson(instance.numberSilly),
      'numberSillySet': instance.numberSillySet
          ?.map((e) => _NumberSillyConverter.instance.toJson(e))
          ?.toList()
    };
```

**Comment by kevmoo** [comment]
Added in `json_serializable` 1.3 - https://github.com/dart-lang/json_serializable/commit/dc882d7da148d00e83b47ff74bddabfb2f6442df
