### ISSUE TITLE
@JsonKey(required: false) not working for Enums

### ISSUE THREAD

**Issue by fhuonder** [dart-lang/json_serializable#334]
Hi all,

Flutter version:
```Flutter 0.8.1-pre.26 • channel unknown • unknown source
Framework • revision 2c1d12d4f7 (4 weeks ago) • 2018-09-05 18:03:43 -0700
Engine • revision de4c7a53f2
Tools • Dart 2.1.0-dev.3.0.flutter-760a9690c2
```
I am using json_serializable in version 1.4.0.

When annotating an enum-field with @JsonKey(required: false) it throws an exception when the field is missing in the JSON.
I assume it is due to the code in the _$enumDecode(...) method that throws an ArgumentError when the source is null ignoring the information from the annotation.

Regards,
Florian

**Comment by kevmoo** [comment]
Do you have `nullable: false` in `@JsonSerializable`?

**Comment by fhuonder** [comment]
Yes there is `nullable:false` set on the `@JsonSerializable`.
If that's the reason: Wouldn't it be correct when the settings in the `@JsonKey` have precedence?

**Comment by kevmoo** [comment]
`required` defaults to false, so you're not changing anything by setting it explicitly. This is a case of overlapping behavior between annotations.

What you want is to set `nullable = true` on your key and I think you'll get the behavior you want.
