### ISSUE TITLE
Output Directory

### ISSUE THREAD

**Issue by bagintz** [dart-lang/json_serializable#347]
Is there a way to put the generated files somewhere other than with the "source" files?  I would like to put all the .g files into a folder to keep my models by themselves.

Thanks

**Comment by kevmoo** [comment]
Already discussed here - https://github.com/dart-lang/json_serializable/issues/306
See https://github.com/dart-lang/json_serializable/issues/306#issuecomment-420030058

I'd do a 👍 on https://github.com/dart-lang/build/issues/1689 if you're interested
