### ISSUE TITLE
ToJson does not convert nested class correctly

### ISSUE THREAD

**Issue by gagaJay** [dart-lang/json_serializable#356]
Hi, Im looking into the Order class example and found that the Item class is not converted to Map.
```
class Order {
  int count;
  int itemNumber;
  bool isRushed;
  Item item; 
   Map<String, dynamic> toJson() => _$OrderToJson(this);
}
```
and the generated part looks like this:

```
Map<String, dynamic> _$OrderToJson(Order instance) {
...
  writeNotNull('item', instance.item);
...
  return val;
}
```

The item in order map is still of Item type, but Im expecting it to be auto converted to Map as well. Im wondering why it does not just add instance.item.tojson() for us? I don't really want to add it manually, otherwise it will be overwritten by regenerating .g file.  
Can someone help? Thanks

**Comment by kevmoo** [comment]
Try using `explicit_to_json = true`.

The package is set up assuming you're using `dart:convert` JSON classes, which handle calling `toJson` for you.
