### ISSUE TITLE
Truncate Strings before calling DateTime.Parse if digit second fraction is more than 6

### ISSUE THREAD

**Issue by MisterJimson** [dart-lang/json_serializable#357]
Flutter 0.11.13 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 58c8489fcd (16 hours ago) • 2018-11-29 19:20:18 -0500
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

Currently when using ```@JsonSerializable()``` attribute on a model with DateTime property the generated code does the following:

```
DateTime.parse(json['myJsonPropertyKey'] as String)
```

This will throw an exception if the date string has more than 6 digits for the second fraction. Example: "2018-11-08T18:25:04.5860769". This is documented here: https://api.dartlang.org/stable/2.1.0/dart-core/DateTime/parse.html

My suggestion is to truncate the second fraction to 6 digits before calling DateTime.parse().

**Comment by kevmoo** [comment]
Good catch. I'm nervous about the overhead involved in adding this for all date times.

@jakemac53 – thoughts?

**Comment by MisterJimson** [comment]
This is an example of a workaround I am using.
```
String stripFractionalSeconds(String dateTime) =>
    dateTime.replaceFirstMapped(RegExp("(\\.\\d{6})\\d+"), (m) => m[1]);

@JsonSerializable()
class AppointmentDateTimeAndFlexibility {
  String preferredAppointmentDateTime;
  @JsonKey(ignore: true)
  DateTime preferredAppointmentDateTimeDate;
  String appointmentFlexibility;

  AppointmentDateTimeAndFlexibility({
    this.preferredAppointmentDateTime,
    this.appointmentFlexibility,
  }) {
    if (preferredAppointmentDateTime != null) {
      preferredAppointmentDateTime =
          stripFractionalSeconds(preferredAppointmentDateTime);
      preferredAppointmentDateTimeDate =
          DateTime.parse(preferredAppointmentDateTime);
    }
  }

  factory AppointmentDateTimeAndFlexibility.fromJson(
          Map<String, dynamic> json) =>
      _$AppointmentDateTimeAndFlexibilityFromJson(json);

  Map<String, dynamic> toJson() =>
      _$AppointmentDateTimeAndFlexibilityToJson(this);

```

**Comment by jakemac53** [comment]
Note that you could use a custom converter to handle this which would work for all DateTime fields in a class with a simple annotation - https://github.com/dart-lang/json_serializable/blob/master/example/lib/json_converter_example.dart

**Comment by MisterJimson** [comment]
Nice, thanks. I figured this was possible but didn't see it in the docs.
```
String _stripFractionalSeconds(String dateTime) =>
    dateTime.replaceFirstMapped(RegExp("(\\.\\d{6})\\d+"), (m) => m[1]);

class DateTimeConverter implements JsonConverter<DateTime, String> {
  const DateTimeConverter();

  @override
  DateTime fromJson(Object json) {
    if (json is String) {
      return DateTime.parse(_stripFractionalSeconds(json));
    } else {
      return null;
    }
  }

  @override
  String toJson(DateTime object) {
    return object?.toIso8601String();
  }
}
```

**Comment by kevmoo** [comment]
Closing this out. The baked-in functionality is meant to handle `DateTime` in Dart only. The suggestion from @jakemac53 is the way to go!
