### ISSUE TITLE
both set defaultValue and fromJson in @JsonKey then defaultValue is not work

### ISSUE THREAD

**Issue by ymback** [dart-lang/json_serializable#361]
I add both defaultValue and fromJson in JsonKey like below
```
  @JsonKey(defaultValue: {}, fromJson: convertFromMap, toJson: convertToMap)
  Map<dynamic, List<dynamic>> map;
```

after run build, the generated code like below
```
map: json['map'] == null
      ? null
      : DialogInfo.convertFromMap(
              json['map'] as Map) ??
          {}
```

then if json['map'] is null, it always return null, which expected is {}

In my opinion, this should generate like this
```
json['map'] == null
      ? {}
      : DialogInfo.convertFromMap(
              json['map'] as Map) ??
          {}
```
or
```
(json['map'] == null
      ? null
      : DialogInfo.convertFromMap(
              json['map'] as Map)
) ??
          {}
```
I know if I don't set defaultValue, only return {} in toJson Function and add nullable: false in JsonKey, it runs ok, but maybe my opinion is a better way to avoid error for people who use it.

**Comment by kevmoo** [comment]
Good issue! I'll take a look!

**Comment by kevmoo** [comment]
The solution: use `nullable: false` instead. Then handle the `null` case in `convertFromMap`.

I'll leave this open to track adding a warning in this case, though. Folks should probably not be using `defaultValue` and `fromJson` together!

```dart
@JsonKey(nullable: false, fromJson: convertFromMap, toJson: convertToMap)
Map<dynamic, List<dynamic>> map;
```

**Comment by ymback** [comment]
Thank you for reply.
I think the solution add `nullable: false` is good enough, this let developers do whatever they want to do in `toJson`.
