### ISSUE TITLE
Split package on generator and annotations

### ISSUE THREAD

**Issue by Aetet** [dart-lang/json_serializable#37]
Hello. 
Thanks for awesome package for json stuff. 
At our project we separate all analyzer, source_gen deps to separate project and use them as cli. This helps migrate on new versions of sdk withour worrying and resolve dependency conflicts between transitive deps. 

Is it possible to split this package on generator and annotations? So forth we can depend at our code directly from annotations and all analyzer stuff will be isolated in another package.

**Comment by ranquild** [comment]
+1 for this. I like approach taken by built_value, where there is separate built_value_generator package.

**Comment by Aetet** [comment]
@kevmoo any thoughts about it?

**Comment by kevmoo** [comment]
Sounds reasonable. Let me ponder...

**Comment by kevmoo** [comment]
Published as `json_serializable` `0.2.4` and **new** `json_annotation` v0.2.0

**Comment by Aetet** [comment]
@kevmoo Thanks a lot. I try it out.
