### ISSUE TITLE
Json error

### ISSUE THREAD

**Issue by AmberWhiteSky** [dart-lang/json_serializable#373]
{
    "entry": {
        "list": [
            {
                "id": "3304785",
                "mid": "5c413500df130740",
                "uuid": "20000003908391",
                "operate": "add",
                "newsid": "6491836537763049779",
                "typeid": "0",
                "source": "2",
                "title": "北京市住建委主任徐贱云做客“市民对话一把手”",
                "createtime": "1547774442",
                "author": "安居北京",
                "content": "2019年1月17日晚，北京市住房和城乡建设委员会主任徐贱云做客“市民对话一把手”大型全媒体直播访谈节目，就完善租购并举的住房制度、老楼加装电梯、老旧小区综合整治等市民普遍关心的问题进行对话交流。",
                "url": "http://m.leju.com/news-bj-6491836537763049779.html",
                "type": "text"
            },
            {
                "id": "3304784",
                "mid": "5c413500df130740",
                "uuid": "20000003908391",
                "operate": "add",
                "newsid": "6491828453149815155",
                "typeid": "0",
                "source": "2",
                "title": "北京新增供应两宗大兴限房价项目用地",
                "createtime": "1547772515",
                "author": "赵昱",
                "content": "1月17日，北京市规划和自然资源委员会新挂牌出让两宗土地，均位于大兴区。",
                "url": "http://m.leju.com/news-bj-6491828453149815155.html",
                "type": "pic",
                "picurl": "http://src.leju.com/imp/imp/deal/24/5d/b/250fa8637b7e8be58c30aa68a75_p24_mk24.jpg"
            },
            {
                "id": "3304783",
                "mid": "5c413500df130740",
                "uuid": "20000003908391",
                "operate": "add",
                "newsid": "6491687455170015929",
                "typeid": "0",
                "source": "2",
                "title": "院子里的中国年 | 引爆童年记忆，重温大院里的新年时光",
                "createtime": "1547738898",
                "author": "",
                "content": "",
                "url": "http://m.leju.com/news-bj-6491687455170015929.html",
                "type": "pic3",
                "piclist": [
                    {
                        "src": "http://src.leju.com/imp/imp/deal/ad/7a/2/9d094d836fb0b56a7154a2307b5_p24_mk24.png"
                    },
                    {
                        "src": "http://src.leju.com/imp/imp/deal/5a/92/d/6a7de0876ffc10318cfa7f3ef23_p24_mk24.png"
                    },
                    {
                        "src": "http://src.leju.com/imp/imp/deal/f6/b7/6/4610b9f89fb201fb64dca9ad692_p24_mk24.png"
                    },
                    {
                        "src": "http://src.leju.com/imp/imp/deal/45/f7/0/241ff6c35fea12338ad678807d0_p24_mk24.png"
                    },
                    {
                        "src": "http://src.leju.com/imp/imp/deal/0e/a1/f/67229f14b331d92f7587f60eb67_p24_mk24.png"
                    },
                    {
                        "src": "http://src.leju.com/imp/imp/deal/02/cd/e/b7821a0c4934e847c22826f8d92_p24_mk24.png"
                    }
                ]
            },
            {
                "id": "3304782",
                "mid": "5c413500df130740",
                "uuid": "20000003908391",
                "operate": "add",
                "newsid": "6491688974233678566",
                "typeid": "0",
                "source": "2",
                "title": "365张全家福，记录大院里的中国年",
                "createtime": "1547739260",
                "author": "",
                "content": "",
                "url": "http://m.leju.com/news-bj-6491688974233678566.html",
                "type": "pic3",
                "piclist": [
                    {
                        "src": "http://src.leju.com/imp/imp/deal/80/f6/f/a3c56219ff9453fab3bce70f2cb_p24_mk24.png"
                    },
                    {
                        "src": "http://src.leju.com/imp/imp/deal/99/22/e/1c601b8f2b9a794a701b28dbf1e_p24_mk24.png"
                    },
                    {
                        "src": "http://src.leju.com/imp/imp/deal/07/79/d/6f8f73507c9fac9f5acdbaaf0fb_p24_mk24.png"
                    },
                    {
                        "src": "http://src.leju.com/imp/imp/deal/e0/dc/8/5ba0d5da4cf381135fa654381cf_p24_mk24.png"
                    },
                    {
                        "src": "http://src.leju.com/imp/imp/deal/e0/4a/8/4ddd10844152a0ae9057d276340_p24_mk24.png"
                    },
                    {
                        "src": "http://src.leju.com/imp/imp/deal/60/6d/5/0fbfd6aae7c309bbed31f46a30a_p24_mk24.png"
                    },
                    {
                        "src": "http://src.leju.com/imp/imp/deal/d8/45/4/c85a49b9cb5cc03116e26d625ea_p24_mk24.png"
                    }
                ]
            },
            {
                "id": "3292619",
                "mid": "1f53796y28203g61",
                "uuid": "20000003908391",
                "operate": "add",
                "newsid": "6440403851937119705",
                "typeid": "0",
                "source": "2",
                "title": "【测试】昌平国瑞熙墅家园已开盘  1400万元一套起",
                "createtime": "1535511935",
                "author": "",
                "content": "",
                "url": "http://m.leju.com/news-ab-6440403851937119705.html",
                "type": "pic",
                "picurl": "http://src.leju.com/imp/imp/deal/80/14/0/71326591c7dcc994d69f817874e_p24_mk24_sX0.jpg"
            }
        ],
        "count": 5
    }
}

this is  my json data,
use json_serializable
the piclist disappear
import 'package:json_annotation/json_annotation.dart'; 
  
part 'collect_bean.g.dart';

@JsonSerializable()
  class collect_bean extends Object {

  @JsonKey(name: 'entry')
  Entry entry;

  collect_bean(this.entry,);

  factory collect_bean.fromJson(Map<String, dynamic> srcJson) => _$collect_beanFromJson(srcJson);

  Map<String, dynamic> toJson() => _$collect_beanToJson(this);

}

  
@JsonSerializable()
  class Entry extends Object {

  @JsonKey(name: 'list')
  List<List> list;

  @JsonKey(name: 'count')
  int count;

  Entry(this.list,this.count,);

  factory Entry.fromJson(Map<String, dynamic> srcJson) => _$EntryFromJson(srcJson);

  Map<String, dynamic> toJson() => _$EntryToJson(this);

}

  
@JsonSerializable()
  class List extends Object {

  @JsonKey(name: 'id')
  String id;

  @JsonKey(name: 'mid')
  String mid;

  @JsonKey(name: 'uuid')
  String uuid;

  @JsonKey(name: 'operate')
  String operate;

  @JsonKey(name: 'newsid')
  String newsid;

  @JsonKey(name: 'typeid')
  String typeid;

  @JsonKey(name: 'source')
  String source;

  @JsonKey(name: 'title')
  String title;

  @JsonKey(name: 'createtime')
  String createtime;

  @JsonKey(name: 'author')
  String author;

  @JsonKey(name: 'content')
  String content;

  @JsonKey(name: 'url')
  String url;

  @JsonKey(name: 'type')
  String type;

  List(this.id,this.mid,this.uuid,this.operate,this.newsid,this.typeid,this.source,this.title,this.createtime,this.author,this.content,this.url,this.type,);

  factory List.fromJson(Map<String, dynamic> srcJson) => _$ListFromJson(srcJson);

  Map<String, dynamic> toJson() => _$ListToJson(this);

}

**Comment by kevmoo** [comment]
You need to have a field in your class for `piclist` or it won't be saved
