### ISSUE TITLE
CheckedFromJsonException: toString() or consistent message field

### ISSUE THREAD

**Issue by isoos** [dart-lang/json_serializable#378]
The `CheckedFromJsonException` does not always have its `message` field populated, nor does it have a toString() that could provide  a helpful message in such cases.

**Comment by kevmoo** [comment]
Uh...help w/ a repro here?

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/json_serializable/commit/64889f0e6bf4e2ee1782282d17fe84abde98996d
