### ISSUE TITLE
@JsonKey(fromJson) Arguments of a constant creation must be constant expressions.

### ISSUE THREAD

**Issue by lukepighetti** [dart-lang/json_serializable#389]
I'm trying to use `@JsonKey(fromJson: (j)=>j)` to make the entire json map available as a field. I get the error `Arguments of a constant creation must be constant expressions.`

Am I doing something wrong? Or has there been an API change?

```dart
@JsonSerializable(createToJson: false)
class Entry {
  final int id;

  @JsonKey(fromJson: _dataFromJson)
  final Map<String, dynamic> data;

  Entry(this.id, this.data);

  _dataFromJson(Map<String, dynamic> input) => input;

  factory Entry.fromJson(Map<String, dynamic> json) => _$EntryFromJson(json);
}

```

<img width="808" alt="screen shot 2019-02-22 at 2 09 41 pm" src="https://user-images.githubusercontent.com/666539/53265154-83cbf480-36ab-11e9-88d1-68028ca8fe9e.png">

**Comment by lukepighetti** [comment]
Ah, its gotta be a static member.

**Comment by MM1132** [comment]
@lukepighetti Hey! Currently I am facing the same problem myself, and I figured out the solution quite quickly, yet it keeps me wondering... why can we just not pass the function anonymously? If you know the answer to that question, please do not hesistate to write it here, thanks a lot! :)
