### ISSUE TITLE
pub finished with exit code 78

### ISSUE THREAD

**Issue by fengqiangboy** [dart-lang/json_serializable#397]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this, please include the entire output
of either `dart --version` or `flutter --version`, depending on what
you're using.

```
$ dart --version
Dart VM version: 2.1.1 (Thu Feb 14 12:04:25 2019 +0100) on "macos_x64"
```

```
$ flutter --version
Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (3 months ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
```
When run build, it error

```
$ flutter packages pub run build_runner build
[INFO] Generating build script...
[INFO] Generating build script completed, took 309ms

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 817ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Found 10 declared outputs which already exist on disk. This is likely because the`.dart_tool/build` folder was deleted, or you are submitting generated files to your source repository.
[SEVERE] Conflicting outputs were detected and the build is unable to prompt for permission to remove them. These outputs must be removed manually or the build can be run with `--delete-conflicting-outputs`. The outputs are: lib/model/response.g.dart
lib/model/mode/bbq_mode_model.g.dart
lib/model/app_config.g.dart
lib/model/file/qiniu_file_model.g.dart
lib/model/user.g.dart
lib/model/multi_language.g.dart
lib/model/rom/rom_model.g.dart
lib/model/rom/rom_info_model.g.dart
lib/model/ecig_type_page_data.g.dart
lib/model/ecig_type.g.dart
pub finished with exit code 78
```

**Comment by fengqiangboy** [comment]
run  `flutter packages pub run build_runner build --delete-conflicting-outputs` and fix

**Comment by cyberpwnn** [comment]
That just deletes all of my outputs and fails fails with exit code 63

**Comment by kevmoo** [comment]
try deleting your `.dart_tool` directory. Rerun `pub get` and then `build`

**Comment by joaquini** [comment]
The only solution that worked was to delete **manually** all `*.g.dart` files and then run `flutter pub run build_runner build`.

**Comment by kevmoo** [comment]
`flutter pub run build_runner clean` should also work

**Comment by abdalazeez1** [comment]
`packages pub run build_runner build --delete-conflicting-outputs`
  should also work

**Comment by venkat-clone** [comment]
```
$flutter packages pub run build_runner build --delete-conflicting-outputs 
[INFO] Generating build script...
[INFO] Generating build script completed, took 1.3s

[INFO] Precompiling build script......
[WARNING] .dart_tool/build/entrypoint/build.dart:11:8: Error: Error when reading '../../../../.pub-cache/hosted/pub.dartlang.org/web3dart-2.4.1/lib/src/builder/builders.dart': No such file or directory
import 'package:web3dart/src/builder/builders.dart' as _i4;
       ^
.dart_tool/build/entrypoint/build.dart:34:10: Error: Undefined name 'abiGenerator'.
    [_i4.abiGenerator],
         ^^^^^^^^^^^^
.dart_tool/build/entrypoint/build.dart:41:9: Error: Undefined name 'deleteSource'.
    _i4.deleteSource,
        ^^^^^^^^^^^^
[INFO] Precompiling build script... completed, took 16.3s

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.

pub finished with exit code 78

```
why I'm getting this error?

**Comment by BATUCHKA** [comment]
> ```
> $flutter packages pub run build_runner build 
> [INFO] Generating build script...
> [INFO] Generating build script completed, took 1.3s
> 
> [INFO] Precompiling build script......
> [WARNING] .dart_tool/build/entrypoint/build.dart:11:8: Error: Error when reading '../../../../.pub-cache/hosted/pub.dartlang.org/web3dart-2.4.1/lib/src/builder/builders.dart': No such file or directory
> import 'package:web3dart/src/builder/builders.dart' as _i4;
>        ^
> .dart_tool/build/entrypoint/build.dart:34:10: Error: Undefined name 'abiGenerator'.
>     [_i4.abiGenerator],
>          ^^^^^^^^^^^^
> .dart_tool/build/entrypoint/build.dart:41:9: Error: Undefined name 'deleteSource'.
>     _i4.deleteSource,
>         ^^^^^^^^^^^^
> [INFO] Precompiling build script... completed, took 16.3s
> 
> [SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
> This is likely caused by a misconfigured builder definition.
> 
> pub finished with exit code 78
> ```
> 
> why I'm getting this error?

have you found your answer?

**Comment by kevmoo** [comment]
Are you all using `package:web3dart`?

**Comment by liaovq** [comment]
> Are you all using `package:web3dart`?

Yes, everything works fine after removing [web3dart](https://pub.dev/packages/web3dart)

**Comment by kevmoo** [comment]
There's pretty likely a bug in web3dart

**Comment by BATUCHKA** [comment]
> > Are you all using `package:web3dart`?
> 
> Yes, everything works fine after removing [web3dart](https://pub.dev/packages/web3dart)

how did you find it? it's can't find in my pubspec.yaml
