### ISSUE TITLE
Option to ignore fields which are not annotated

### ISSUE THREAD

**Issue by leisim** [dart-lang/json_serializable#399]
Most of the time, my json classes have many fields which have nothing to do with json. If I do not add `@JsonKey(ignore: true)` to them, they will be null after deserialization.

It would be really useful to have an option in `JsonSerializable` to only use fields which are explicitly annotated with `@JsonKey`

**Comment by kevmoo** [comment]
Could you provide an example?

**Comment by leisim** [comment]
**test.dart:**
```dart
import 'package:json_annotation/json_annotation.dart';

part 'test.g.dart';

@JsonSerializable(createToJson: false)
class TestJsonModel {
  @JsonKey(name: "myName")
  String onlyJsonField;

  int status = 5;

  String note = "This is not a json field";

  bool edited = false;

  static TestJsonModel fromJson(Map<String, dynamic> json) {
    return _$TestJsonModelFromJson(json);
  }
}
```

**test.g.dart:**
```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'test.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

TestJsonModel _$TestJsonModelFromJson(Map<String, dynamic> json) {
  return TestJsonModel()
    ..onlyJsonField = json['myName'] as String
    ..status = json['status'] as int
    ..note = json['note'] as String
    ..edited = json['edited'] as bool;
}
```

The fields "status", "note" and "edited" are not from json but used by the app. This is why they should neither be serialized nor parsed.
But I didn't add `@JsonKey(ignore: true)` so they will be `null` after deserialization.

It would be helpful to set `@JsonSerializable(createToJson: false, onlyUseAnnotated: true)` so json_serializable only considers annotaded fields.

**Comment by kevmoo** [comment]
Ah! That should be doable, in theory, but I worry about the added complexity. Will ponder...

**Comment by Rohansi** [comment]
Yes, please. A way to whitelist would be very useful for introducing persistence to classes.

**Comment by kevmoo** [comment]
Turns out this is pretty easy to implement. PR in flight...

**Comment by leisim** [comment]
Thank you! :+1:
