### ISSUE TITLE
flutter bigint not parsing

### ISSUE THREAD

**Issue by jackselvam** [dart-lang/json_serializable#412]
Error running JsonSerializableGenerator
Could not generate `fromJson` code for `categoryId`.
None of the provided `TypeHelper` instances support the defined type.
package:etrade/models/viewmodels/products.dart:7:16
  ╷
7 │   final BigInt categoryId;
  │                ^^^^^^^^^^

**Comment by kevmoo** [comment]
Just published 2.1 w/ this fix
