### ISSUE TITLE
fail:  flutter packages pub run build_runner build --verbose

### ISSUE THREAD

**Issue by hatjs880328s** [dart-lang/json_serializable#414]
flutter packages pub run build_runner build --verbose
[INFO] Generating build script...
[INFO] Generating build script completed, took 355ms

[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Building new asset graph...
[INFO] BuildDefinition:Building new asset graph completed, took 661ms

[INFO] BuildDefinition:Checking for unexpected pre-existing outputs....
[INFO] BuildDefinition:Found 7 declared outputs which already exist on disk. This is likely because the`.dart_tool/build` folder was deleted, or you are submitting generated files to your source repository.
[SEVERE] BuildDefinition:
Conflicting outputs were detected and the build is unable to prompt for permission to remove them. These outputs must be removed manually or the build can be run with `--delete-conflicting-outputs`. The outputs are: lib/Model/user.g.dart
lib/Model/IIExcMODELS/IIExcMainListModel.g.dart
lib/Model/IIExcMODELS/IIExcFolderModel.g.dart
lib/Model/IIExcMODELS/IIExcSidebarList.g.dart
lib/Model/LoginToken.g.dart
lib/Model/MoveCar/MoveCarModel.g.dart
lib/Model/MoveCar/MoveCarSmallModel.g.dart
pub finished with exit code 78

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      pubInteractively (package:flutter_tools/src/dart/pub.dart:186:5)
<asynchronous suspension>
#2      PackagesPassthroughCommand.runCommand (package:flutter_tools/src/commands/packages.dart:148:11)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#10     Future._complete (dart:async/future_impl.dart:473:7)
#11     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#12     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#18     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

**Comment by kevmoo** [comment]
did you try to run `build_runner clean` and then your build again?

**Comment by anztrax** [comment]
thanks that's works for me @kevmoo 🎉

**Comment by ImranSefat** [comment]
I have the same problem. Ran flutter packages pub run build_runner clean then flutter packages pub run build_runner build but didn't work
