### ISSUE TITLE
API docs don't list or explain annotations

### ISSUE THREAD

**Issue by zoechi** [dart-lang/json_serializable#416]
https://pub.dartlang.org/documentation/json_serializable/latest/

See also https://stackoverflow.com/questions/55179700/flag-to-ignore-serialization-of-property-build-runner/55179822 and the comments below the answer.

**Comment by kevmoo** [comment]
Yup. Pull requests welcome.

**Comment by kevmoo** [comment]
Check out the docs on 2.1 – better?
