### ISSUE TITLE
can't build any file

### ISSUE THREAD

**Issue by drdevelop** [dart-lang/json_serializable#421]
Succeeded after 6.7s with 0 outputs (2 actions)

**Comment by kevmoo** [comment]
Run `build_runner clean` first. Then paste the output of `build_runner build --verbose`

**Comment by drdevelop** [comment]
first i  carried out `flutter packages pub run build_runner clean` , then carried out `flutter packages pub run build_runner build --verbose`, but the command line returned to me is `Build:Succeeded after 11.1s with 0 outputs (2 actions)`

**Comment by kevmoo** [comment]
Do you have any files annotated w/ `@JsonSerializable`?

**Comment by drdevelop** [comment]
@kevmoo There is a @JsonSerializable annotation, or 2 actions will not be captured. The example I use is the user.dart example of flutter's official website.

**Comment by kevmoo** [comment]
You're following along here? https://flutter.dev/docs/development/data-and-backend/json#creating-model-classes-the-json_serializable-way

Do you have these items in your pubspec?

```yaml
dependencies:
  # Your other regular dependencies here
  json_annotation: ^2.0.0

dev_dependencies:
  # Your other dev_dependencies here
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
```

**Comment by drdevelop** [comment]
@kevmoo yes

**Comment by kevmoo** [comment]
Hrm......

run a clean again, then run `build --verbose` and paste the output?

**Comment by hasimyerlikaya** [comment]
There was same problem in my project and I found solution.
Problem was, class name and file name did not same.
When I rename file as class name, the problem was solved.

**Comment by kevmoo** [comment]
That's interesting @hasimyerlikaya – as far as I know, the name of the file should have no affect.

**Comment by hasimyerlikaya** [comment]
For **model.dart**  must be **part "model.g.dart";**
Not class name, sorry @kevmoo

**Comment by drdevelop** [comment]
@kevmoo this is my output:

**Comment by drdevelop** [comment]
[INFO] Generating build script...
[INFO] Generating build script completed, took 367ms

[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 11.8s

[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Building new asset graph...
[INFO] BuildDefinition:Building new asset graph completed, took 676ms

[INFO] BuildDefinition:Checking for unexpected pre-existing outputs....
[INFO] BuildDefinition:Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Build:Running build...
[INFO] Heartbeat:1.0s elapsed, 0/1 actions completed.
[FINE] json_serializable on test/widget_test.dart:Running JsonSerializableGenerator - 1 of 2
[FINE] json_serializable on test/widget_test.dart:Running JsonLiteralGenerator - 2 of 2
[INFO] Build:Running build completed, took 6.8s

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 41ms

[INFO] Build:Succeeded after 6.8s with 0 outputs (2 actions)

**Comment by drdevelop** [comment]
@kevmoo My source construction file code is as follows：

```dart
import 'package:json_annotation/json_annotation.dart';
part 'user.g.dart';

@JsonSerializable()

class User {
  User(this.name, this.email);

  String name;
  String email;

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);

  Map<String, dynamic> toJson() => _$UserToJson(this);
}
```

**Comment by drdevelop** [comment]
I don't know which step is misconfigured, because it's entirely in accordance with the official website, can you help me look at it? @kevmoo and @hasimyerlikaya

**Comment by drdevelop** [comment]
my filename is `user.dart`

**Comment by kevmoo** [comment]
What's in your `build.yaml` file?

For some reason, the builder is not running against any code in your lib directory.

Also: WHERE is `user.dart`?

**Comment by drdevelop** [comment]
The location of the user.dart file is  in / -> app -> model -> user.dart  
 
There is no build.yaml file in my project. Is this file not necessary?

**Comment by drdevelop** [comment]
The location of the user.dart file must be specified, I remember it seems to be in any folder of the project.

**Comment by drdevelop** [comment]
@kevmoo 
It turns out that this library can only convert files in the lib directory, because I used to write web projects, so I think the lib directory is the tool library. I will use the app directory as my project directory. Is there any way to change it? Is the effective directory?

**Comment by kevmoo** [comment]
I don't think we support files in `app` – unless you explicitly put it in the sources in `build.yaml`

**Comment by drdevelop** [comment]
```yaml
targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          include:
          - app/model/*
          - lib/*
```

**Comment by drdevelop** [comment]
This is my build.yaml file, lib/* is in effect, but app/model/* does not take effect.

**Comment by drdevelop** [comment]
Well, I tested that I found that the model files in the lib and example directories in build.yaml can detect and generate the corresponding g.dart, but my custom app directory is not working. I think since the example directory line, Should also support customizing other directory names.

**Comment by inoryshu** [comment]
大佬们。这个问题怎么解决的呀。我现在也是这个问题无法解决

**Comment by kevmoo** [comment]
@jakemac53 @natebosch – do we only support some top-level directories?

**Comment by jakemac53** [comment]
By default we only include the directories specified in the [pub package layout conventions](https://www.dartlang.org/tools/pub/package-layout).

You can customize the files that are included for your app though, using the `sources` config for a target:

```yaml
targets:
  $default:
    # Override the default source globs, we don't include `app/` by default
    sources:
      - pubspec.*
      - lib/**
      - app/**
```

**Comment by drdevelop** [comment]
@jakemac53 @jakemac53  Good! It turned out that my previous build. yaml configuration was a bit of a problem, as you said, the configuration has achieved the desired effect, thank you.

**Comment by kevmoo** [comment]
@jakemac53 – wondering if there is something we could do to make this easier?

Maybe print a warning if `generate_for` includes files not in `sources`?

**Comment by natebosch** [comment]
> Maybe print a warning if `generate_for` includes files not in `sources`?

That get's a little tricky since they are both globs and the overlap of globs isn't always easy to reason about.

It's plausible that we could detect when there is a `genarate_for` glob that matches zero sources, but we'll need to be cautious not to take the defaults provided with the builder into account for that...

Tracking at https://github.com/dart-lang/build/issues/2111

**Comment by amreniouinnovent** [comment]
My issue was funny...I put the models folder outside lib folder for flutter

**Comment by kevmoo** [comment]
> My issue was funny...I put the models folder outside lib folder for flutter

Rarely (if ever) should you have model code outside of `lib`
