### ISSUE TITLE
Support value as object name

### ISSUE THREAD

**Issue by yhua537** [dart-lang/json_serializable#423]
With class as:
```
class Person{
  String id;
  String name;
  int age;
}
```

```
class PersonList(
  Map<String, Person> peopleMap = new HashMap<String, Person>();
)
```

What will be the annotation setup or fromJson/toJson to be able to encode/decode to this format?
```
{
  personlist:{
    "idPerson1":{
      "name":"Peter", 
      "age":20
    }, 
    "idPerson2":{
      "name":"John",
      "age":21
    },
  }
}
```

I am using
Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (5 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

**Comment by kevmoo** [comment]
You may not be able to use `JsonSerializable` for this class. This library is designed to well with classes that have hand-rolled serialization, though. You may have to implement this one by hand.

**Comment by yhua537** [comment]
For anyone who interested, I actually almost there with 2 small steps to be able use JsonSerializable: 

```
class Person{
  @JsonKey(ignore: true)
  String id;

  String name;
  int age;
}
class topLv{
  @JsonKey(name: 'personlist', fromJson: _fromJsonToPersonMap)
  Map<String, Person> peopleMap = new HashMap<String, Person>();
  // the key of the map needs to be the id to have {id: object} format
}

//most of the code is auto generated, added ..id = k at the end to manually set the id back 
Map<String, Person> _fromJsonToPersonMap(Map<String, dynamic> json) {
  return json.map((k, v) => MapEntry(
      k as String,
      v == null
          ? null
          : Person.fromJson((v as Map)?.map(
              (k1, e) => MapEntry(k1 as String, e),
            ))
        ..id = k));
}
```
