### ISSUE TITLE
How to handle Uint8List type ?

### ISSUE THREAD

**Issue by benoitverstraete** [dart-lang/json_serializable#429]
Hi,

I try to use the json_serializable package to convert Uint8List (byte[]) in JSON but I have this error message :

> Error running JsonSerializableGenerator
Could not generate `fromJson` code for `imageContent`.
None of the provided `TypeHelper` instances support the defined type.
   ╷
27 │   Uint8List imageContent;
   │             ^^^^^^^^^^^^
   ╵

Here is the source code :

```
@JsonKey(name: 'image_content')
Uint8List imageContent;
```

Could you please tell me how to handle the Uint8List type with your package ?

Thanks a lot

**Comment by kevmoo** [comment]
I'm likely NOT going to add support for these types.

**Comment by lingster** [comment]
In case anyone arrives here, my solution is to convert the Uint8List to base64 like this:

```
/// This converter converts to base64 which is supported in json
class Uint8ListToStringConverter implements JsonConverter<Uint8List?, String> {
  const Uint8ListToStringConverter();

  @override
  Uint8List? fromJson(String json) {
    if (json == "") return null;
    return Uint8List.fromList(base64Decode(json));
  }

  @override
  String toJson(Uint8List? object) {
    if (object == null) return "";
    return base64Encode(object);
  }
}
```
