### ISSUE TITLE
mixin on mixin fails

### ISSUE THREAD

**Issue by janosroden** [dart-lang/json_serializable#448]
The following code crashes the generator:

```dart
mixin MyMixinBase on Object {
  int prop;
}

mixin MyMixin on MyMixinBase {}

@JsonSerializable()
class MyClass with MyMixinBase, MyMixin {}
```

I think the direct cause is the usage of `isSuperOf()` in `field_helpers.dart:_FieldsSet::_sortByLocation()` which handles `extends` hierarchy only. At least replacing that call with `isAssignableFrom()` solved the error.

However I'm not sure this is the proper way to fix it, please check it.

### flutter --version
Flutter 1.3.8 • channel beta • https://github.com/flutter/flutter.git
Framework • revision e5b1ed7a7f (5 weeks ago) • 2019-03-06 14:23:37 -0800
Engine • revision f4951df193
Tools • Dart 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

**Comment by kevmoo** [comment]
Can you run the build with `--verbose` and send me the stack?

**Comment by kevmoo** [comment]
Also, attach your `pubspec.lock` file so I can see versions.

**Comment by janosroden** [comment]
Hi, unfortunately I can't do that before Monday.

Please wait, or just copy-paste my example into your [example project](https://github.com/dart-lang/json_serializable/blob/master/example/lib/example.dart) and build.
I tried it with the latest version of json_serializable. I also ran the tests with my patch and they're ok.

Stack trace was something like:
_generate
...
collectAllMembers or similar
...
_sortByLibrary or something
...
TypeChecker::isSuperOf

and `isSuperOf()` tried to access `element` on a `null` (it got a mixin, but it assumed it has a base type until Object).


Cheers

**Comment by janosroden** [comment]
Hi, I'm a little bit confused because the example what I sent earlier works now.. wierd.
But in my project still not, so I started to triangle again and this is the minimal requirement:

```dart
mixin MyMixin {
  int prop1;
}

@JsonSerializable()
class MyClass with MyMixin {
   int prop2
}
```

I created a [gist](https://gist.github.com/janosroden/c988d871c6073b01eb78205e36e8e2fb) from both pubspec.yaml and build runner output.

The issue occurs with properties too.

I used your [example project](https://github.com/dart-lang/json_serializable/tree/master/example) (master / 93f8da4)

**Comment by kevmoo** [comment]
Bug found. Fixing now!

**Comment by kevmoo** [comment]
PR to fix is open. Will release immediately once that lands

**Comment by janosroden** [comment]
Great, thanks!

**Comment by kevmoo** [comment]
https://pub.dartlang.org/packages/json_serializable/versions/2.2.1 😄
