### ISSUE TITLE
uuid type is not supported?

### ISSUE THREAD

**Issue by keyeMyria** [dart-lang/json_serializable#449]
### runn flutter packages pub run build_runner build  got:

`[SEVERE] json_serializable:json_serializable on lib/src/domain/model/user.model.dart:
Error running JsonSerializableGenerator
Could not generate `fromJson` code for `ids`.
None of the provided `TypeHelper` instances support the defined type.
package:zlito/src/domain/model/user.model.dart:13:8
   ╷
13 │   Uuid ids;
   │        ^^^
   ╵`

Uuid class is [dart-uuid](https://github.com/Daegalus/dart-uuid)

**Comment by kevmoo** [comment]
You'll have to write a custom converter for this.

See https://github.com/dart-lang/json_serializable/blob/master/example/lib/json_converter_example.dart
