### ISSUE TITLE
Feature request: Programmatic API

### ISSUE THREAD

**Issue by hh10k** [dart-lang/json_serializable#476]
I am writing a sourcegen package to generate some boilerplate, but I'd like my generated classes to also have `toJson` and `fromJson` functions.  It would be nice to make use of your work for this, but I don't see a way to do this without mocking the AST in some way, since there's no intermediate model between parsing the AST and generating code.

Thanks!

**Comment by hh10k** [comment]
So, I took a stab at refactoring json_serializable to do what I wanted, and discovered there's no clear way of decoupling parsing and generating without a lot of code churn.  Do you have any advice on how else I can do it?

**Comment by hh10k** [comment]
So, I took a stab at refactoring json_serializable to do what I wanted, and discovered there's no clear way of decoupling parsing and generating without a lot of code churn.  Do you have any advice on how else I can do it?

**Comment by kevmoo** [comment]
Could you explain a bit more of what you want? Do you want to call the generator methods without using any analyzer types?

**Comment by hh10k** [comment]
It might be easier to explain what I'm doing, since the exact problem I'm trying to solve can probably be solved in a simpler way.  I would only like something that doesn't use analyser for code generation because that is how my code is structured.

My sourcegen package takes an interface (abstract class) that defines only field getters, and then generates classes (mutable and immutable) that implement that interface.  It's basically `built_value` but without the builder callback stuff.

Both classes could share the same `toJson` implementation that works against the base interface.  Each class would have a `fromJson` factory that creates an object using a constructor taking named arguments.  Since JsonSerializable/JsonKey attributes trigger the json_serializable generator I would need to provide configuration with my own attributes.

**Comment by kevmoo** [comment]
You may have to roll your own thing.

`TypeHelper` bits are public, so you can build on them - https://pub.dev/documentation/json_serializable/latest/type_helper/type_helper-library.html

**Comment by hh10k** [comment]
Thanks for the link. I've been a bit time poor so I haven't had time to try it all out, but I may at least try EnumHelper. The other helpers are either reasonably trivial or recurse maps/iterables in a way that won't work with generated classes that analyser doesn't see (and interprets as `dynamic`). My implementations have ended up being a bit more complicated.

I'll continue to try to keep my code compatible with yours though. My intention is not to reinvent everything.
