### ISSUE TITLE
nested objects are not converted to Map<String, dynamic>

### ISSUE THREAD

**Issue by KorbinianMossandl** [dart-lang/json_serializable#497]
It seems nested objects don't get converted to `Map<String, dynamic>` even though the are annotated with `@JsonSerializable()` and have a `Map<String, dynamic> toJson()` method.
It works fine the other way around.

To make sure i tried with your example Person class from https://github.com/dart-lang/json_serializable/blob/master/example/lib/example.dart and even there only the Person itself will get properly serialized. `Order` and `Item` objects will not and even `Order.date` will not get serialized to int even though it is enforced with `@JsonKey(fromJson: _dateTimeFromEpochUs, toJson: _dateTimeToEpochUs)` but just stay a `DateTime` object.

Is there anything i am doing wrong or is this a bug?

**Comment by kevmoo** [comment]
See https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
