### ISSUE TITLE
type 'int' is not a subtype of type 'String' in type cast

### ISSUE THREAD

**Issue by jackselvam** [dart-lang/json_serializable#500]
build_runner  generating json['id'] as String code which is not working in latest dart.

i am getting "type 'int' is not a subtype of type 'String' in type cast" error.
if i change "json['id'] as String" to json['id'].toString(), it's working.

please fix the issue.

**Comment by kevmoo** [comment]
Please include your source Dart class and the generated output

**Comment by jackselvam** [comment]
@JsonSerializable()
class LookupModel {
  final BigInt id;
  final String value;
  LookupModel(this.id,this.value);
  
  factory LookupModel.fromJson(Map<String, dynamic> json) =>
      _$LookupModelFromJson(json);
  Map<String, dynamic> toJson() => _$LookupModelToJson(this);
}

into 

LookupModel _$LookupModelFromJson(Map<String, dynamic> json) {
  return LookupModel(
      json['id'] == null ? null : BigInt.parse(json['id'] as String),
      json['value'] as String);
}

Map<String, dynamic> _$LookupModelToJson(LookupModel instance) =>
    <String, dynamic>{'id': instance.id?.toString(), 'value': instance.value};

**Comment by kevmoo** [comment]
`BigInt` is too big for `int` ... so if you're bringing in JSON values with `{'int': 42}` that won't work – unless you use a custom converter.

**Comment by jackselvam** [comment]
latest dart version doesn't supporting "json['id'] as String".
Same i was using two months before, it was working

**Comment by aelahmar** [comment]
Same issue here:
{"timeStamp":"1582112243770"}
String b = data['timeStamp'];

type 'String' is not a subtype of type 'int'

**Comment by JonasABR** [comment]
i'm having the same issue. Does the custom converter work @jackselvam  ?

**Comment by kevmoo** [comment]
The code I've implemented here assumes the source value is a STRING `"42"` not a number `42`. This is to ensure we round-trip all valid BigInt values – which go well beyond what `int` supports.

It sounds like you'd like to support decoding JSON numbers here, too?

**Comment by srvstvnhl** [comment]
If i use the toString() it is not working. and if i use the as String, then it is throwing the error that is mentioned in the issue thread.

**Comment by kevmoo** [comment]
What's the JSON you're trying to parse?

**Comment by exeptionerror** [comment]
[[Solved] type ‘int’ is not a subtype of type ‘String’ error in Dart](https://fluttercorner.com/type-int-is-not-a-subtype-of-type-string-error-in-dart/)

**Comment by gb4dev** [comment]
Hello, is there anything new about this problem ?

**Comment by gb4dev** [comment]
> Hello, is there anything new about this problem ?

So i finally use double instead of BigInt for unsigned int 64

**Comment by kevmoo** [comment]
You can also create a custom converter to handle this case: https://pub.dev/packages/json_serializable#custom-types-and-custom-encoding
