### ISSUE TITLE
Support deserialization to default enum value for unsupported values

### ISSUE THREAD

**Issue by Lisenish** [dart-lang/json_serializable#504]
I would prefer to have enum field set to provided default value instead of  "is not one of the supported values" ArgumentError. I don't want my app crashes on any Back End change.

**Comment by kevmoo** [comment]
Reasonable...

**Comment by kevmoo** [comment]
> I would prefer to have enum field set to provided default value instead of "is not one of the supported values" ArgumentError. I don't want my app crashes on any Back End change.

You could annotate an enum value as `unknown`. Gotcha.

**Comment by CoderSpinoza** [comment]
@kevmoo How can this be achieved? I see that #360 hasn't been merged.

**Comment by kevmoo** [comment]
I didn't like the approach of #360 – although we could do something similar on second thought.

**Comment by CoderSpinoza** [comment]
> > I would prefer to have enum field set to provided default value instead of "is not one of the supported values" ArgumentError. I don't want my app crashes on any Back End change.
> 
> You could annotate an enum value as `unknown`. Gotcha.

By above, you mean something like below?

```dart
enum ApiErrorCause {
  @JsonValue(-1)
  INTERNAL_ERROR,
  @JsonValue(-2)
  ILLEGAL_PARAMS,
  @JsonUnknown
  UNKNOWN
}
```

**Comment by CoderSpinoza** [comment]
@kevmoo @Lisenish @beastoin

Could we discuss on how to support this? I believe this is pretty much necessary for any API response field that we want to express as enum. It won't be very clean to use custom JsonConverter for every enum field.

**Comment by Lisenish** [comment]
@CoderSpinoza I think while this issue is open unfortunately there is no different approach right now except JsonConverter.

**Comment by kevmoo** [comment]
This turns out to be a bit more gnarly than I feared. Digging in...

**Comment by kevmoo** [comment]
@CoderSpinoza @Lisenish – PR in flight https://github.com/dart-lang/json_serializable/pull/516

Please take a look

**Comment by CoderSpinoza** [comment]
@kevmoo Thanks a lot for such a fast merge :) I will wait for next release!

**Comment by Lisenish** [comment]
@kevmoo Awesome work, thank you! 👍

**Comment by beastoin** [comment]
Good to hear that unknown enum has been supported. Thank @CoderSpinoza @Lisenish and @kevmoo for your hard working. Happy coding 👨‍💻
