### ISSUE TITLE
using with the new code generation in Flutter?

### ISSUE THREAD

**Issue by maks** [dart-lang/json_serializable#506]
I'm trying to understand if it's possible to use this package with the [new Flutter code generation](https://github.com/flutter/flutter/wiki/Code-generation-in-Flutter) ?

Should it be possible to wrap the functionality to run the json (de)serialisation code generation with a Flutter builder?

**Comment by kevmoo** [comment]
I believe so – @jonahwilliams ?

**Comment by maks** [comment]
So to answer my own question, yes it worked just fine to use `json_serializable` with Flutter's codegen, BUT [that functionality is actually currently broken](https://github.com/flutter/flutter/issues/42003) so I should say it *will* be possible once that's fixed.
