### ISSUE TITLE
dart linter avoid_as

### ISSUE THREAD

**Issue by amorenew** [dart-lang/json_serializable#507]
I wonder if you could replace `as` in the generated files so dart lint accepts it?

https://dart-lang.github.io/linter/lints/avoid_as.html

or add `//ignore: avoid_as` when you using as

**Comment by amorenew** [comment]
Also, I have a request class and I just need `ToJson `in it so dart lint show me `unused_element `for 
```
ConfigRequest _$ConfigRequestFromJson(Map<String, dynamic> json) {
  return ConfigRequest(json['access_code'] as String);
}
```

**Comment by kevmoo** [comment]
Mark `JsonSerializable(create_factory: false)` to stop generating that function.

For `avoid_as` – we need to use `as` in this case. I'd (personally) recommend against this lint in general.

**Comment by kevmoo** [comment]
Er, `createFactory: false`

**Comment by amorenew** [comment]
@kevmoo  Thank you
