### ISSUE TITLE
DateTime type parsed on 'fromJson' method

### ISSUE THREAD

**Issue by cTatu** [dart-lang/json_serializable#533]
I think there may be some tricky bussiness that I can't figure out going on here. The problem is that I have a class with a `DateTime` field and a json file with the following entry: 
```
{
    "timestamp": "Wed Aug 21 2019 01:58:52 GMT+0200" // Already a DateTime
}
```
So since the `fromJson` method wants a decoded json converted to `Map`, by decoding the above entry the result type is directly a `DateTime` type object and when the generated code wants to construct the `Foo` object it will cast it to a string, regardless of it's type and throw an excpetion.
**Source code**
```dart
@JsonSerializable(nullable: false)
class Foo {
    final DateTime timestamp;
     ...
}
```
**Generated .g.dart code**
```dart
Foo _$FooFromJson (Map<String, dynamic> json) {
  return Foo (DateTime.parse(json['timestamp'] as String), ...);
}
```

It's there a way to supress the type conversion and make the Serialization go raw on that attribute? Because for now my workaround is to delete the parsing part of the generated code by hand on each build.

Thank you!

#### Flutter Version
```
> flutter --version
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (4 months ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
```

**Comment by kevmoo** [comment]
"It's there a way to supress the type conversion and make the Serialization go raw on that attribute?"

I'm not sure what you mean here. Could you write out the code you WANT to be generated for this Foo class?

**Comment by cTatu** [comment]
I guess I was thinking about having a named field on the JsonKey annotation class that would not parse that attribute, something like:
```dart
  @JsonKey(parse: false)
  final DateTime timestamp;
```
But then I realised that I can override the `fromJson` function so I created a static method for this field to cast the json value directly to DateTime:
```dart
@JsonSerializable(nullable: false)
class Foo {
    @JsonKey(fromJson: _rawDateTime)
    final DateTime timestamp;

    static DateTime _rawDateTime(t) => t as DateTime;
     ...
}
```
At the end there were a solution, I just needed to look more carefully. Thank you!

**Comment by Puspharaj** [comment]
This is issue still pops up in pre build version of flutter

**Comment by kevmoo** [comment]
> This is issue still pops up in pre build version of flutter

Explain @Puspharaj ?
