### ISSUE TITLE
Consider supporting `Set`s in constructors

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/json_serializable#54]
Consider a class like:

```
class MyThing {
  final Set<int> myInts;

  MyThing(this.myInts);
}
```

Today the generated `fromJson` constructor would end up trying to pass in an `Iterable<int>` to the constructor, which won't work. The workaround is:

```
class MyThing {
  final Set<int> myInts;

  MyThing(Iterable<int> myInts) : this.myInts = myInts.toSet();
}
```

...but ideally that wouldn't be necessary :).

fwiw, for `List` fields it will automatically call `toList` on the iterable before passing it in.

**Comment by kevmoo** [comment]
Reasonable. PRs welcome!
