### ISSUE TITLE
Problem with parsing json data obtained from nested network requests

### ISSUE THREAD

**Issue by Taco55** [dart-lang/json_serializable#540]
How do I parse a json that contains references to data that needs to be fetched via other network requests?

For example, consinder the following json obtained from an arbitray endpoint: 
```
{
    "id": "1111",
    "example": "value",
    "other_objects": [
        {
            "object_id": "1234"
        },
        {
            "object_id": "5678"
        }
    ]
}
```
This json contains references to the id's of `other_object`'s of which the data can be obtained from another endpoint. For example, to obtain :
```
{
    "id": "1234",
    "other_example": 22
}
```

How can I make requests to both endpoints and serialize the json data all together to a plain model class?

Ideally, I would like to add a `@JsonKey` with a `fromJson` method to make the second network request, but a `factory` construction does not allow async methods. 

Is this possible to perform with `json_serializable`? And what would be the best approach to for this?

**Comment by kevmoo** [comment]
I'd do this in two layers. Create one layer of "raw" objects that map to exactly what's on the wire and then another layer that handles gluing things together.
