### ISSUE TITLE
@JsonKey(toJson: staticMethod)

### ISSUE THREAD

**Issue by lookfirst** [dart-lang/json_serializable#546]
Something changed after upgrading and re-running the builder that is showing up in my git diff.... Is there a reason why the `_$GpuToJson` method no longer runs the id through the static method?

```
@JsonSerializable(includeIfNull: false, nullable: true, explicitToJson: true)
class Gpu {
  @JsonKey(toJson: normalizeId, nullable: true)
  String id;
}
```

![image](https://user-images.githubusercontent.com/85355/65951132-98564380-e469-11e9-970d-310a9f9fdcb3.png)

**Comment by kevmoo** [comment]
https://github.com/dart-lang/sdk/issues/38641 is the root cause, I'm sure.

We need a new pkg:analyzer released!

**Comment by lookfirst** [comment]
@kevmoo Great, thanks. Glad it isn't just me! I'll close this then.
