### ISSUE TITLE
Error during code generation "getter 'parameters' was called on null"

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/json_serializable#548]
[SEVERE] json_serializable:json_serializable on lib/src/modules.dart:
Error running JsonSerializableGenerator
NoSuchMethodError: The getter 'parameters' was called on null.
Receiver: null
Tried calling: parameters
dart:core                                                              Object.noSuchMethod
package:json_serializable/src/type_helper_ctx.dart 113:25              _convertData
package:json_serializable/src/type_helper_ctx.dart 91:24               new _ConvertPair
package:json_serializable/src/type_helper_ctx.dart 45:40               TypeHelperCtx._pairFromContext       
package:json_serializable/src/type_helper_ctx.dart 43:45               TypeHelperCtx.deserializeConvertData 
package:json_serializable/src/type_helpers/convert_helper.dart 49:34   ConvertHelper.deserialize
package:json_serializable/src/type_helper_ctx.dart 62:29               TypeHelperCtx.deserialize.<fn>       
dart:core                                                              Iterable.firstWhere
package:json_serializable/src/type_helper_ctx.dart 66:46               TypeHelperCtx._run
package:json_serializable/src/type_helper_ctx.dart 59:65               TypeHelperCtx.deserialize
package:json_serializable/src/decode_helper.dart 183:14                DecodeHelper._deserializeForField    
package:json_serializable/src/decode_helper.dart 37:9                  DecodeHelper.createFactory.deserializeFun
package:json_serializable/src/decode_helper.dart 282:30                _writeConstructorInvocation.<fn>     
dart:core                                                              StringBuffer.writeAll
package:json_serializable/src/decode_helper.dart 280:12                _writeConstructorInvocation
package:json_serializable/src/decode_helper.dart 98:14                 DecodeHelper.createFactory
package:json_serializable/src/json_serializable_generator.dart 143:28  _GeneratorHelper._generate

**Comment by jakemac53** [comment]
I confirmed that changing back to analyzer 0.38.4 (from 0.38.5) resolves this issue

**Comment by jakemac53** [comment]
cc @scheglov

**Comment by scheglov** [comment]
I think I have already seen this wrong way to access `ExecutableElement` referenced in a constant.
But I don't remember if it was in `json_serializable` or another packages.

```patch
Index: json_serializable/lib/src/type_helper_ctx.dart
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- json_serializable/lib/src/type_helper_ctx.dart	(revision 0295d1ef7c3eb24dc508f02334ae155ee0278be2)
+++ json_serializable/lib/src/type_helper_ctx.dart	(date 1570565888000)
@@ -106,9 +106,7 @@
     return null;
   }
 
-  final type = objectValue.type as FunctionType;
-
-  final executableElement = type.element as ExecutableElement;
+  final executableElement = objectValue.toFunctionValue();
 
   if (executableElement.parameters.isEmpty ||
       executableElement.parameters.first.isNamed ||
```

**Comment by jakemac53** [comment]
Thanks, I can land the fix

**Comment by jakemac53** [comment]
@scheglov do you know if that api has been around for a long time or what version I need to require to get it?

**Comment by natebosch** [comment]
> I think I have already seen this wrong way to access `ExecutableElement` referenced in a constant.
> But I don't remember if it was in `json_serializable` or another packages.

Looks like https://github.com/dart-lang/source_gen/pull/430

**Comment by jakemac53** [comment]
Ok so it looks like `>=0.37.1` then is required

**Comment by scheglov** [comment]
Yes, it was added in `0.37.1`.

**Comment by SergeShkurko** [comment]
For me helps: https://github.com/dart-lang/json_serializable/issues/252#issuecomment-406771115
