### ISSUE TITLE
Upgrade to analyzer 0.39.x

### ISSUE THREAD

**Issue by natebosch** [dart-lang/json_serializable#552]
The `InheritanceManager` class is removed in favor of `InheritanceManager3`. I haven't yet figure out the replacement API for `getMembersInheritedFromClasses` is...

Likely related: https://github.com/dart-lang/json_serializable/issues/531

**Comment by kevmoo** [comment]
@scheglov – any ideas?

**Comment by scheglov** [comment]
`getInheritedMap` maybe?

**Comment by natebosch** [comment]
I think that's the likely replacement.

This will take significant refactoring because I need to get a `TypeSystem` passed through to all the places that need it now that didn't before. I also don't think I can synchronously get a `TypeSystem` so everything will need to become async.

**Comment by scheglov** [comment]
If you have a `ResolvedUnitResult`, it has `typeSystem`.
If you have an `Element`, you can ask `element.context.typeSystem`.

**Comment by natebosch** [comment]
> If you have an `Element`, you can ask `element.session.typeSystem`.

This is what I'm doing. Since its async it means any place I do this must be async. I'm trying  a refactor now where I get it once and then hold on to it so the rest of the methods don't need to become async, only the outermost one.

**Comment by natebosch** [comment]
One nasty bit here.

There is a public `TypeSystem` at [`package:analyzer/dart/element/type_system.dart`](https://github.com/dart-lang/sdk/blob/1a611e1d72cccdda70fa32c29fe15de463423cae/pkg/analyzer/lib/dart/element/type_system.dart#L11) however I can't use it.

Classes like [`InheritanceManager3`](https://github.com/dart-lang/sdk/blob/1a611e1d72cccdda70fa32c29fe15de463423cae/pkg/analyzer/lib/src/dart/element/inheritance_manager3.dart#L35) (which the changelog tells me to use over `InheritanceManager`) takes a private [`TypeSystem`](https://github.com/dart-lang/sdk/blob/1a611e1d72cccdda70fa32c29fe15de463423cae/pkg/analyzer/lib/src/generated/type_system.dart#L2375) instead of the public one.

I'll use the `src` import everywhere for now. Is there a plan for a _public_ `InheritanceManager` that I can use without `src` imports?

**Comment by scheglov** [comment]
I'm not aware about any plans to expose `ImheritanceManager` as a public API.
@stereotype441 for future planning.

**Comment by natebosch** [comment]
Unfortunately I think we are going to need a breaking change.

https://github.com/dart-lang/json_serializable/blob/78cba3d5eb292817357c4044e3fbee0410350d76/json_serializable/lib/src/type_helpers/convert_helper.dart#L40-L42

This is a publicly visible class. We can no longer do this work without an instance of `TypeSystem`. We can't add a `TypeSystem` field or argument to this method without a breaking change.

**Comment by scheglov** [comment]
If you have access to a `ClassElement`, e.g. [here](https://github.com/dart-lang/json_serializable/blob/master/json_serializable/lib/src/type_helper.dart#L13), you can access `TypeSystem`.

**Comment by natebosch** [comment]
> If you have access to a `ClassElement`, e.g. [here](https://github.com/dart-lang/json_serializable/blob/master/json_serializable/lib/src/type_helper.dart#L13), you can access `TypeSystem`.

We could do that if we make the method async. I'll explore that option too.

Is there a synchronous way to go from `ClassElement` to `TypeSystem`? `element.session.typeSystem` is a `Future<TypeSystem>`.

**Comment by scheglov** [comment]
I don't understand why. You have `TypeHelperContextWithConvert context`, which `extends TypeHelperContext`, that has `ClassElement get classElement`. Or is this `classElement` filled asynchronously?

**Comment by scheglov** [comment]
Oh, you are right, `AnalysisSession.typeSystem` is async.

**Comment by scheglov** [comment]
In theory you could use `Element.context.typeSystem`, which will return a pre-computed `TypeSystem`. The only reason `AnalysisSession.typeSystem` is async is that you could get `AnalysisSession` without a result, but it is never the case for you, I think. Hm... Maybe we should just add a sync version.

**Comment by kevmoo** [comment]
> https://github.com/dart-lang/json_serializable/issues/557

I don't think this is related at all!

**Comment by trevorwang** [comment]
> > #557
> 
> I don't think this is related at all!

Should I remove the link from here?

**Comment by isoos** [comment]
Is there an estimate when this will be done?

**Comment by kevmoo** [comment]
@scheglov could you help here?

CC @natebosch @jakemac53

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/125995 added `typeProvider` and `typeSystem` to `LibraryElement`. There was also NNBD related bug in this change, so it was fixed in https://dart-review.googlesource.com/c/sdk/+/126060.

And, because we have `typeSystem` in `LibraryElement`, so available to `ClassElement`, `InheritanceManager3` will not need `TypeSystem` at all, will be landed as https://dart-review.googlesource.com/c/sdk/+/126083.

We plan to publish a new non-breaking version of `analyzer`, probably `0.39.2`. It might or might not have the `InheritanceManager3` change, depending on timing.
