### ISSUE TITLE
How can i use class name as data type in Json Serializing

### ISSUE THREAD

**Issue by ashanjayasundara** [dart-lang/json_serializable#555]
I want to do something like below

```dart
import 'package:json_annotation/json_annotation.dart';

part 'MyClassOne.g.dart';
part 'MyClassTwo.g.dart';

@JsonSerializable()
class MyClassOne {
  MyClassTwo two;

  MyClassOne(this.two);

  factory MyClassOne.fromMappedJson(Map<String, dynamic> json) =>
      _$MyClassOneFromJson(json);

  Map<String, dynamic> toJson() => _$MyClassOneToJson(this);
}

@JsonSerializable()
class MyClassTwo {
  String a;

  MyClassTwo(this.a);

  factory MyClassTwo.fromMappedJson(Map<String, dynamic> json) =>
      _$MyClassTwoFromJson(json);

  Map<String, dynamic> toJson() => _$MyClassTwoToJson(this);
}
````

Is this possible to do with existing releases

**Comment by kevmoo** [comment]
I'm not sure what you want to do. What do you want in the generated code?

**Comment by ashanjayasundara** [comment]
@kevmoo Actually i want to generate code **(MyClassOne)** which has the member attribute with the type of  another class **(MyClassTwo)** so when i calling `MyClassOne.fromMappedJson(Map<String, dynamic> json)` method in MyClassOne then i should able to generate the code without an issue

**Comment by kevmoo** [comment]
@ashanjayasundara – I'm still confused here...
