### ISSUE TITLE
parse DateTime with UTC support 

### ISSUE THREAD

**Issue by Aetet** [dart-lang/json_serializable#56]
Hello.
For DateTime helper there's no way to deserialize UTC time. Is there workaround for this?

**Comment by kevmoo** [comment]
If you had code that handled UTC parsing, you could customize your `JsonSerialiazableGenerator` to with a custom `TypeHelper`.

**Comment by Aetet** [comment]
Thanks in advance

**Comment by bonflintstone** [comment]
> If you had code that handled UTC parsing, you could customize your `JsonSerialiazableGenerator` to with a custom `TypeHelper`.

I am running into the same issue now, but I cannot find any documentation about how to configure my own typeHelpers. Could you give me some pointers as to how to go about it?

**Comment by shilangyu** [comment]
> I am running into the same issue now, but I cannot find any documentation about how to configure my own typeHelpers. Could you give me some pointers as to how to go about it?

Same problem here, there does not seem to be any docs/examples about it
