### ISSUE TITLE
Linter >=0.1.103 depends on analyzer ^0.39.1 and json_serializable >=3.2.3 depends on analyzer >=0.37.1 <0.39.0

### ISSUE THREAD

**Issue by Katekko** [dart-lang/json_serializable#560]
The new version of Linter depends on analyzer 0.39.1, can json_serializable update too?

![image](https://user-images.githubusercontent.com/13632735/68673436-794fd480-0532-11ea-9c5b-d2656268f7da.png)

**Comment by kevmoo** [comment]
We're blocked on https://github.com/dart-lang/json_serializable/issues/552 – need to find a way to migrate to the latest analyzer

CC @natebosch
