### ISSUE TITLE
travis ci failing on PR

### ISSUE THREAD

**Issue by bsutton** [dart-lang/json_serializable#567]
I recently issued a pull request (PR #565).

The PR passes all unit tests on my local machine.
However when I push the PR, travis fails as follows:

https://travis-ci.org/dart-lang/json_serializable/builds/616900949?utm_source=github_status&utm_medium=notification

The key problem is that checked_yaml test won't run:

During the dependency resolution phase I see:

```
 json_annotation 3.0.1 from path ../json_annotation (overridden)
 json_serializable 3.2.5 from path ../json_serializable (overridden)
```

Then when it attempts to build:
```
Because checked_yaml depends on json_serializable ^3.2.5 which doesn't match
  any versions, version solving failed.
```

The version no's during the resolution phase are correct.

So I'm guessing this is some sort of build order issue?

I would have assumed that travis would first build any dependencies.
As such I would have expected json_serializable to have been built and therefore the 3.2.5 version would be available on the path.

Clearly this is not happening as the checked_yaml build isn't finding 3.2.5.

I don't even know where to start to solve this issue.

Can you give me any pointers?

Brett

**Comment by kevmoo** [comment]
You need to change checked_yaml to have a path dependency, I think...

**Comment by bsutton** [comment]
So I'm meant to check in code with a path?

The existing version of checked_yaml's pubspec doesn't use a path and I assume that it passes the ci tests?

**Comment by kevmoo** [comment]
Try again w/ the latest? I just bumped some things that'll likely help!

**Comment by bsutton** [comment]
So I've made progress on this.
I had to go through the child packages and ensure that all of them required Dart 2.6 or the unit tests would fail.
I also worked out how to correctly use dependency_overrides so now the paths should work locally and when published without any changes being required.

I'm now having problem with travis failing on some unit tests that I don't believe have anything to do with my code changes.

As such I'm not certain how to go about fixing them.

For example the readme_test.dart in the example project reads both the pubspec.yaml and readme.md and compares them against a few lines of fixed content.
Both files are compared to the same fixed content (a dependencies section from a pubspec).

This clearly makes no sense.
For the moment I've marked this unit test to be skipped.

The other failure is the ensure_build_test.dart again in the examples project.

You can see the details here:
https://travis-ci.org/dart-lang/json_serializable/jobs/628989987?utm_medium=notification&utm_source=github_status

I'm not certain how to proceed?

**Comment by kevmoo** [comment]
You need to run `pub run builder_runner build` in `_test_yaml` directory and commit that code.
