### ISSUE TITLE
how to avoid "as" type error?

### ISSUE THREAD

**Issue by xiaohongjun0509** [dart-lang/json_serializable#568]
hi, i have meet some problems that thanks trouble me a lot and ask for some help.
eg:
for the code:
json['channelId'] as int

if channelId is not a int type ,the code above will case a error.
so why not you add a type chenker to avoid this error and set a default value if not the same type?
 
waiting for your reply. Thank you

**Comment by huhuang03** [comment]
I think automatic type cast is good, because some server-end not do well in type define.

**Comment by huhuang03** [comment]
If the field is string and json type is int.

Foo(json['xx'] as string) cause type error
and Foo(json['xx'].toString()) works fine.

**Comment by huhuang03** [comment]
Hello, you can define all your class field as string, and use this.

https://github.com/dart-lang/json_serializable/blob/master/example/lib/example.dart#L47

```
  @JsonKey(fromJson: intSafeToString)
  String MarginTop;   //": "0"

  static String intSafeToString(dynamic jsonVal) {
      return jsonVal?.toString()?? "";
  }
```

**Comment by kevmoo** [comment]
This is not a lint we can avoid. We have to convert the contents of the `dynamic` JSON values to concrete types.
