### ISSUE TITLE
Handling classes with generic fields

### ISSUE THREAD

**Issue by ShehanMadushanka** [dart-lang/json_serializable#573]
I've gone through all the issues and find a way to implement generic response. Found a similar issues but couldn't find a fix for this.
My issue is when converting json in to generic, object return as a **null**. 

> **PS: Object is converting to json with no issues.**

Json response: 
```
{
  "error": "success",
  "status": 200,
  "data": {
    "sessionTimeout": "5000"
  }
}
```

Base Response Class:

```
import 'package:json_annotation/json_annotation.dart';

part 'base_response.g.dart';

@JsonSerializable()
class BaseResponse<T> {
  String error;
  int status;
  @JsonKey(fromJson: _dataFromJson, toJson: _dataToJson, name: 'data')
  T data;

  BaseResponse({this.error, this.status, this.data});

  factory BaseResponse.fromJson(Map<String, dynamic> json) {
    print(json);
    return _$BaseResponseFromJson<T>(json);
  }

  Map<String, dynamic> toJson() => _$BaseResponseToJson(this);
}

T _dataFromJson<T>(Map<String, dynamic> input) {
  return input['data'] as T;
}
```

<img width="1134" alt="Screenshot 2019-12-12 at 17 17 05" src="https://user-images.githubusercontent.com/25446951/70709749-a5ae6a80-1d03-11ea-8119-37314b2bebb4.png">

Generated BaseResponse:

```
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'base_response.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

BaseResponse<T> _$BaseResponseFromJson<T>(Map<String, dynamic> json) {
  return BaseResponse<T>(
    error: json['error'] as String,
    status: json['status'] as int,
    data: _dataFromJson(json['data'] as Map<String, dynamic>),
  );
}

Map<String, dynamic> _$BaseResponseToJson<T>(BaseResponse<T> instance) =>
    <String, dynamic>{
      'error': instance.error,
      'status': instance.status,
      'data': _dataToJson(instance.data),
    };

```

**Comment by kevmoo** [comment]
Show me how you're calling that code! Your test code is hidden behind the pop-up!

**Comment by ShehanMadushanka** [comment]
Thanks for the response @kevmoo!
Here is the test code.

<img width="839" alt="Screenshot 2019-12-26 at 09 59 51" src="https://user-images.githubusercontent.com/25446951/71457976-9bda3c00-27c6-11ea-8999-fe632bd0fc7b.png">

**Comment by kevmoo** [comment]
This is an interesting case.

Will you know `T` before you try to parse the response or do you want to create a typed response based on the contents of `data`?

This is a pretty specialized case that doesn't map well to this package. You may have to layer something on top if you want the right types.
