### ISSUE TITLE
Can convert json to the dart class？

### ISSUE THREAD

**Issue by GanZhiXiong** [dart-lang/json_serializable#574]
This web site (https://javiercbk.github.io/json_to_dart/) can convert json to dart class files, I want to know json_serializable can do?

**Comment by PHPadawan** [comment]
Yes, read this https://medium.com/flutter-community/generate-the-code-to-parse-your-json-in-flutter-c68aa89a81d9

**Comment by kevmoo** [comment]
> This web site (https://javiercbk.github.io/json_to_dart/) can convert json to dart class files, I want to know json_serializable can do?

This is not something this package does.

**Comment by GanZhiXiong** [comment]
@PHPadawan   I want to generate the dart class from a json file？
I don't seem to have found it in the website you sent. Can you describe it
Thanks you！

**Comment by terrylucas** [comment]
Paste this into the JSON text area:

[
    {
        "thisSupported": [
            {
                "cool": true
            },
            {
                "test": "test String"
            },
            {
                "nested": [
                    {
                        "nested100": 100
                    }
                ]
            }
        ]
    }
]

This will generate the Dart classes thisSupported and nested with the
properties cool, test and nested100.

**Comment by GanZhiXiong** [comment]
< Paste this into the JSON text area:
Hi, Where is the JSON text area?

**Comment by terrylucas** [comment]
Goto the https://javiercbk.github.io/json_to_dart/ that Kevin mentioned.

[image: image.png]

The caret under JSON  and to the right of the number 1 is where you paste,
the JSON payload from the above email, click on the Generate Dart button
then Dart classes will be emitted.
