### ISSUE TITLE
Make JsonKey support inheritance

### ISSUE THREAD

**Issue by lucasgmagalhaes** [dart-lang/json_serializable#575]
I have this situation:

```dart
class Column extends JsonKey {
  const Column({String name}) : super(name: name);
}

class User {
  @Column(name: "user_name")
  String name;
}
```
When `user.g.dart` is generated, the property `name` isn't changed to `user_name`. Asking in Gitter, I was informed that the builder doesn't support JsonKey inheritance, so I would like to check if it can be done.

**Comment by kevmoo** [comment]
It might be possible. Are you just trying to avoid duplication here?

My only concern: I've been able to make changes assuming there are no subclasses. Supporting this may make future changes more difficult.

Open to discuss.

**Comment by lucasgmagalhaes** [comment]
Yes, just avoid duplications. I was able to inherit `JsonSerializable` annotation with no problem. So I thought that with `JsonKey` will be able either.

**Comment by lirantzairi** [comment]
I'm looking for the same thing and for the same reason. I have lots of fields in different classes all annotated with `@JsonKey(required: true, disallowNullValue: true)`. I wish there was a way to subclass JsonKey with custom classes in order to avoid code duplication.

Thanks.

**Comment by kevmoo** [comment]
Hrm. This might be doable. I'll take a look.

**Comment by kevmoo** [comment]
See https://github.com/dart-lang/json_serializable/pull/623

**Comment by kevmoo** [comment]
v3.3.0 is out now w/ this change!

**Comment by lirantzairi** [comment]
Thanks!

**Comment by kevmoo** [comment]
Please let us know how it works out for you!

**Comment by lirantzairi** [comment]
@kevmoo I think I found a small issue, or maybe I'm missing something... At first I have this simple class with regular JsonKey:

```
@JsonSerializable(createToJson: false)
class MyModel {
  static String _fromJson(String val) => val;

  @JsonKey(fromJson: _fromJson) final String name;

  MyModel(this.name);

  factory MyModel.fromJson(Map<String, dynamic> json) => _$MyModelFromJson(json);
}
```

The generated function looks ok:

```
MyModel _$MyModelFromJson(Map<String, dynamic> json) {
  return MyModel(
    MyModel._fromJson(json['name'] as String),
  );
}
```

But if I create a custom subclass of JsonKey and use it, like this:

```
class MyJsonKey extends JsonKey {
  const MyJsonKey({
    Object defaultValue,
    bool disallowNullValue,
    Function fromJson,
    bool ignore,
    bool includeIfNull,
    String name,
    bool nullable,
    bool required,
    Function toJson,
    Object unknownEnumValue,
  }) : super(
    defaultValue: defaultValue,
    disallowNullValue: disallowNullValue,
    fromJson: fromJson,
    ignore: ignore,
    includeIfNull: includeIfNull,
    name: name,
    nullable: nullable,
    required: required,
    toJson: toJson,
    unknownEnumValue: unknownEnumValue,
  );
}

@JsonSerializable(createToJson: false)
class MyModel {
  static String _fromJson(String val) => val;

  @MyJsonKey(fromJson: _fromJson) final String name;

  MyModel(this.name);

  factory MyModel.fromJson(Map<String, dynamic> json) => _$MyModelFromJson(json);
}
```

Then it ignores my _fromJson function. This is the new generated code:

```
MyModel _$MyModelFromJson(Map<String, dynamic> json) {
  return MyModel(
    json['name'] as String,
  );
}
```

**Comment by Miiite** [comment]
@lirantzairi I observed the same behavior. If you inherit from JsonKey, and specify values for toJson and fromJson functions, those are ignored during the code generation.
So inheritence works, but not for those two properties ... :(

**Comment by lirantzairi** [comment]
@kevmoo Please re-open this. We still can't use fromJson and toJson

**Comment by bbattulga** [comment]
yes want it to work here too

**Comment by bbattulga** [comment]
One probably a hacky solution is do something like this

<img width="533" alt="Screen Shot 2021-01-23 at 13 03 13" src="https://user-images.githubusercontent.com/67428071/105569312-b3924400-5d7b-11eb-989e-9fc3fd47dec9.png">

and the generated code is
<img width="533" alt="Screen Shot 2021-01-23 at 13 06 32" src="https://user-images.githubusercontent.com/67428071/105569335-d6245d00-5d7b-11eb-9a53-be7be27d8aad.png">

Which was enough to solve my problem

**Comment by bbattulga** [comment]
@lirantzairi

**Comment by lirantzairi** [comment]
Opened a new issue for this: https://github.com/google/json_serializable.dart/issues/1057
