### ISSUE TITLE
import of dart:mirrors is not supported in the current Dart runtime

### ISSUE THREAD

**Issue by NsAveek** [dart-lang/json_serializable#577]
dart version : 2.7.0
flutter version : 1.12.13+hotfix.5
json_serializable: ^3.2.3
build_runner: ^1.0.0

Syncing files to device iPhone 11 Pro Max...
Error -32000 received from application: Could not run configuration in engine.
Restarted application in 6,571ms.
[VERBOSE-2:shell.cc(199)] Dart Error: error: import of dart:mirrors is not supported in the current Dart runtime
[VERBOSE-2:engine.cc(198)] Could not prepare to run the isolate.
[VERBOSE-2:engine.cc(137)] Engine not prepare and launch isolate.

**Comment by kevmoo** [comment]
`json_serializable` shouldn't be in the runtime of your Flutter application. Did you follow the configuration pointed to in the readme?

**Comment by rezaUniqe** [comment]
in my case i put dependency on top of flutter it worked for me like this:
dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.2.0

  flutter_test:
    sdk: flutter

**Comment by mado-bohsali** [comment]
> `json_serializable` shouldn't be in the runtime of your Flutter application. Did you follow the configuration pointed to in the readme?

What's the resolution?

**Comment by kevmoo** [comment]
@mado-bohsali – what does your pubspec look like?

**Comment by mado-bohsali** [comment]
> @mado-bohsali – what does your pubspec look like?

json_serializable under dev_dependencies

But I am now into SQFLite. Have you used it before for saving models?

**Comment by kevmoo** [comment]
> But I am now into SQFLite. Have you used it before for saving models?

I have not...

**Comment by mado-bohsali** [comment]
Can you help me with JSON serialization of classes and SharedPreferences?

**Comment by kevmoo** [comment]
> Can you help me with JSON serialization of classes and SharedPreferences?

Start by looking at the examples – https://github.com/google/json_serializable.dart/tree/master/example – and doing a bit of searching on Google/YouTube.

I strongly recommend asking How-to questions on StackOverflow.
