### ISSUE TITLE
Library import prefixes are ignored.

### ISSUE THREAD

**Issue by isoos** [dart-lang/json_serializable#586]
On `JsonKey`, when the function of `toJson` and `fromJson` uses library prefix (e.g. `import 'x.dart' as x;` `JsonKey(fromJson: x.myFunc)`), the generated code does not include the library prefix (it becomes `myFunc` instead of `x.myFunc`).

Similar thing happens when using an prefix-imported `JsonConverter`.

**Comment by kevmoo** [comment]
Duplicate of https://github.com/dart-lang/json_serializable/issues/19

Very much known. just a lot of work to deal with. PRs welcome 😄
