### ISSUE TITLE
Float Nan conversion failed

### ISSUE THREAD

**Issue by Gopinathp** [dart-lang/json_serializable#588]
Float variable which is Nan value, conversion failed when using gRPC from json serialzable library.

Converting object to an encodable object failed: NaN
#0      _JsonStringifier.writeObject (dart:convert/json.dart:649:7)
#1      _JsonStringifier.writeMap (dart:convert/json.dart:730:7)
#2      _JsonStringifier.writeJsonValue (dart:convert/json.dart:685:21)
#3      _JsonStringifier.writeObject (dart:convert/json.dart:640:9)
#4      _JsonStringifier.writeList (dart:convert/json.dart:700:9)
#5      _JsonStringifier.writeJsonValue (dart:convert/json.dart:679:7)
#6      _JsonStringifier.writeObject (dart:convert/json.dart:640:9)
#7      _JsonStringifier.writeMap (dart:convert/json.dart:730:7)
#8      _JsonStringifier.writeJsonValue (dart:convert/json.dart:685:21)
#9      _JsonStringifier.writeObject (dart:convert/json.dart:640:9)
#10     _JsonStringifier.writeList (dart:convert/json.dart:697:7)
#11     _JsonStringifier.writeJsonValue (dart:convert/json.dart:679:7)
#12     _JsonStringifier.writeObject (dart:convert/json.dart:640:9)
#13     _JsonStringifier.writeMap (dart:convert/json.dart:730:7)
#14     _JsonStringifier.writeJsonValue (dart:convert/json.dart:685:21)
#15     _JsonStringifier.writeObject (dart:convert/json.dart:640:9)
#16     _JsonStringifier.writeMap (dart:convert/json.dart:730:7)
#17     _JsonStringifier.writeJsonValue (dart:convert/json.dart:685:21)
#18     _JsonStringifier.writeObject (dart:convert/json.dart:640:9)
#19     _JsonStringifier.writeList (dart:convert/json.dart:697:7)
#20     _JsonStringifier.writeJsonValue (dart:convert/json.dart:679:7)
#21     _JsonStringifier.writeObject (dart:convert/json.dart:640:9)
#22     _JsonStringifier.writeMap (dart:convert/json.dart:730:7)
#23     _JsonStringifier.writeJsonValue (dart:convert/json.dart:685:21)
#24     _JsonStringifier.writeObject (dart:convert/json.dart:640:9)
#25     _JsonStringifier.writeMap (dart:convert/json.dart:730:7)
#26     _JsonStringifier.writeJsonValue (dart:convert/json.dart:685:21)
#27     _JsonStringifier.writeObject (dart:convert/json.dart:640:9)
#28     _JsonStringifier.writeList (dart:convert/json.dart:700:9)
#29     _JsonStringifier.writeJsonValue (dart:convert/json.dart:679:7)
#30     _JsonStringifier.writeObject (dart:convert/json.dart:640:9)
#31     _JsonStringifier.writeMap (dart:convert/json.dart:730:7)
#32     _JsonStringifier.writeJsonValue (dart:convert/json.dart:685:21)
#33     _JsonStringifier.writeObject (dart:convert/json.dart:640:9)
#34     _JsonStringifier.writeList (dart:convert/json.dart:697:7)
#35     _JsonStringifier.writeJsonValue (dart:convert/json.dart:679:7)
#36     _JsonStringifier.writeObject (dart:convert/json.dart:640:9)
#37     _JsonStringifier.writeMap (dart:convert/json.dart:730:7)
#38     _JsonStringifier.writeJsonValue (dart:convert/json.dart:685:21)
#39     _JsonStringifier.writeObject (dart:convert/json.dart:640:9)
#40     _JsonStringStringifier.printOn (dart:convert/json.dart:836:17)
#41     _JsonStringStringifier.stringify (dart:convert/json.dart:821:5)
#42     JsonEncoder.convert (dart:convert/json.dart:257:30)
#43     JsonCodec.encode (dart:convert/json.dart:168:45)
#44     jsonEncode (dart:convert/json.dart:82:10)
#45     GeneratedMessage.writeToJson (package:protobuf/src/protobuf/generated_message.dart:204:27)
#46     DataProvider.persistData (package:eglu4_0/providerbase.dart:47:29)
<asynchronous suspension>
#47     HierarchyDataProvider.getData (package:eglu4_0/hierarchyPresenter/hierarchyviewdataprovider.dart:32:13)
<asynchronous suspension>
#48     DataProvider.loadData (package:eglu4_0/providerbase.dart:28:7)
#49     new DataProvider (package:eglu4_0/providerbase.dart:22:5)
#50     new HierarchyDataProvider (package:eglu4_0/hierarchyPresenter/hierarchyviewdataprovider.dart:10:32)
#51     HierarchyDataProviderWidget.build (package:eglu4_0/hierarchyPresenter/hierarchyviewwidget.dart:20:38)
#52     StatelessElement.build (package:flutter/src/widgets/framework.dart:4392:28)
#53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4324:15)
#54     Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#55     StatelessElement.update (package:flutter/src/widgets/framework.dart:4399:5)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#57     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5577:14)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5577:14)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#62     Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#63     StatelessElement.update (package:flutter/src/widgets/framework.dart:4399:5)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#67     ProxyElement.update (package:flutter/src/widgets/framework.dart:4658:5)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#71     StatefulElement.update (package:flutter/src/widgets/framework.dart:4514:5)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#74     Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#75     StatelessElement.update (package:flutter/src/widgets/framework.dart:4399:5)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#77     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1147:36)
#78     SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1079:34)
#79     Iterable.forEach (dart:core/iterable.dart:279:30)
#80     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1105:24)
#81     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1050:7)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#83     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5263:32)
#84     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5689:17)
#85     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:202:11)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#87     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5577:14)
#88     Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#89     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5577:14)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#91     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5577:14)
#92     Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#94     Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#95     StatelessElement.update (package:flutter/src/widgets/framework.dart:4399:5)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#97     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5577:14)
#98     Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#100    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#101    StatefulElement.update (package:flutter/src/widgets/framework.dart:4514:5)
#102    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#103    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5577:14)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#106    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#107    StatelessElement.update (package:flutter/src/widgets/framework.dart:4399:5)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#110    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#111    ProxyElement.update (package:flutter/src/widgets/framework.dart:4658:5)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#113    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5577:14)
#114    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#116    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#117    StatefulElement.update (package:flutter/src/widgets/framework.dart:4514:5)
#118    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#120    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#121    ProxyElement.update (package:flutter/src/widgets/framework.dart:4658:5)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#124    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#125    StatelessElement.update (package:flutter/src/widgets/framework.dart:4399:5)
#126    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#127    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#128    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#129    StatelessElement.update (package:flutter/src/widgets/framework.dart:4399:5)
#130    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#132    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#133    ProxyElement.update (package:flutter/src/widgets/framework.dart:4658:5)
#134    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#136    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#137    ProxyElement.update (package:flutter/src/widgets/framework.dart:4658:5)
#138    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#139    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5263:32)
#140    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5689:17)
#141    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#143    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#144    StatefulElement.update (package:flutter/src/widgets/framework.dart:4514:5)
#145    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#146    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#147    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#148    ProxyElement.update (package:flutter/src/widgets/framework.dart:4658:5)
#149    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#151    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#152    StatefulElement.update (package:flutter/src/widgets/framework.dart:4514:5)
#153    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#154    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5577:14)
#155    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#156    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#157    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#158    StatelessElement.update (package:flutter/src/widgets/framework.dart:4399:5)
#159    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#160    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5577:14)
#161    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#162    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#163    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#164    StatefulElement.update (package:flutter/src/widgets/framework.dart:4514:5)
#165    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#166    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#167    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#168    StatefulElement.update (package:flutter/src/widgets/framework.dart:4514:5)
#169    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#170    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#171    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#172    ProxyElement.update (package:flutter/src/widgets/framework.dart:4658:5)
#173    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#174    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#175    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#176    ProxyElement.update (package:flutter/src/widgets/framework.dart:4658:5)
#177    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#178    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#179    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#180    StatefulElement.update (package:flutter/src/widgets/framework.dart:4514:5)
#181    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#182    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#183    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#184    StatefulElement.update (package:flutter/src/widgets/framework.dart:4514:5)
#185    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#186    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#187    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#188    StatefulElement.update (package:flutter/src/widgets/framework.dart:4514:5)
#189    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#190    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5577:14)
#191    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#192    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#193    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#194    StatelessElement.update (package:flutter/src/widgets/framework.dart:4399:5)
#195    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#196    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5577:14)
#197    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#198    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5577:14)
#199    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#200    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#201    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#202    StatefulElement.update (package:flutter/src/widgets/framework.dart:4514:5)
#203    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#204    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5263:32)
#205    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5689:17)
#206    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#207    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#208    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#209    StatefulElement.update (package:flutter/src/widgets/framework.dart:4514:5)
#210    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#211    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5577:14)
#212    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#213    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#214    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#215    StatefulElement.update (package:flutter/src/widgets/framework.dart:4514:5)
#216    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#217    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5577:14)
#218    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#219    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#220    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#221    StatefulElement.update (package:flutter/src/widgets/framework.dart:4514:5)
#222    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#223    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5577:14)
#224    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#225    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#226    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#227    StatefulElement.update (package:flutter/src/widgets/framework.dart:4514:5)
#228    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#229    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#230    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#231    StatelessElement.update (package:flutter/src/widgets/framework.dart:4399:5)
#232    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#233    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#234    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#235    StatefulElement.update (package:flutter/src/widgets/framework.dart:4514:5)
#236    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#237    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5577:14)
#238    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#239    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#240    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#241    ProxyElement.update (package:flutter/src/widgets/framework.dart:4658:5)
#242    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
#243    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#244    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5577:14)
#245    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#246    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#247    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#248    StatefulElement.update (package:flutter/src/widgets/framework.dart:4514:5)
#249    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#250    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#251    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#252    StatelessElement.update (package:flutter/src/widgets/framework.dart:4399:5)
#253    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#254    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5577:14)
#255    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#256    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#257    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#258    ProxyElement.update (package:flutter/src/widgets/framework.dart:4658:5)
#259    Element.updateChild (package:flutter/src/widgets/framework.dart:3080:15)
#260    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4344:16)
#261    Element.rebuild (package:flutter/src/widgets/framework.dart:4048:5)
#262    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2532:33)
#263    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:796:20)
#264    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#265    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1108:15)
#266    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1047:9)
#267    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:856:7)
#268    Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#269    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#270    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#271    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

Is it really an issue? For general questions consider starting with Stack
Overflow:
https://stackoverflow.com/questions/tagged/dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/build

**Comment by kevmoo** [comment]
JSON does not support `NaN` – see https://www.json.org/json-en.html

You'll have to write a custom converter to turn it into – `null`?
