### ISSUE TITLE
Type casting ignores NNBD

### ISSUE THREAD

**Issue by hongyiweiwu** [dart-lang/json_serializable#590]
Consider the code below
```dart
@JsonSerializable()
class Example {
    @JsonKey(nullable: true)
    List<String>? val;

    const Example(this.val);

    <boilerplate>
}
```

the generated fromJson method will look like
```dart
return Example((json['val'] as List)?.map(e => e as String)?.toList())
```

This currently results in a warning by dart analyzer since we're casting json['val'] to a non-null type `List` so the null-aware access operator isn't necessary. In this case though a more appropriate cast might be `as List?`.

**Comment by kevmoo** [comment]
We're a way off from making this package ready for "null safety" (previously known as NNDB)
