### ISSUE TITLE
Change name of a variable

### ISSUE THREAD

**Issue by MalcolmMielle** [dart-lang/json_serializable#594]
Hi,

I'm not sure if it's possible to change the name of variable after serialization. Let's say I have a variable named "var1" that i changed to "var2" for some reason. I won't be able to import my old json file with my class member updated as it is.

I see that there is a field_rename option but I found no explanation on how to use it.

Thanks for the help,

Best,

**Comment by kevmoo** [comment]
`@JsonKey(name: 'json key name')` is the way to go!

**Comment by akshaybhange** [comment]
can we use multiple names for the same variable?

this is not working
```
  @JsonKey(name: 'product_variations')
  @JsonKey(name: 'variations')
  final List<ProductVariation> productVariations;
```
