### ISSUE TITLE
Static method instead of factory contructor

### ISSUE THREAD

**Issue by imtoori** [dart-lang/json_serializable#595]
Is there a reason why using json_serializable I should use a factory constructor instead of a static method?

I would need to use a static method, but I'm wondering about the downsides

**Comment by kevmoo** [comment]
Now that the language has optional "new", it's less of an issue.

Even generated code that references your class with "do the right thing" `MyClass.fromJson` will work the same whether it's a factory or a static function.

It mostly comes down to convention at this point.
