### ISSUE TITLE
Allow deserialize into subclasses

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/json_serializable#597]
Hi, thanks for the wonderful library! This is like a feature request since there seems no existing supply.

For instance, suppose we have (ignoring unrelated details):

```
class A { Animal animal; String fieldInA;}
abstract class Animal { String fieldInBaseClass; }
class Dog extends Animal { String name; }
class Human extends Animal { int id; }
```

Then I want to serialize and de-serialize the "animal" into concrete classes. For instance, the following object:
```
A a1 = A(animal: Dog(fieldInBaseClass: 'base', name: 'hi'), fieldInA:'a');
A a2= A(animal: Human(fieldInBaseClass: 'base', id: 42), fieldInA:'a');
```
should be able to *be converted back and forth with* the following json string:
```
{fieldInA: 'a', animal: {type: 'Dog', fieldInBaseClass: 'base', name: 'hi'}}
{fieldInA: 'a', animal: {type: 'Human', fieldInBaseClass: 'base', id: 42}}
```

Thanks very much for any reply!

**Comment by kevmoo** [comment]
You could absolutely create `factory Animal.fromJson(...) { ... }` that inspects the JSON content and forwards to right subclass `fromJson`.

**Comment by fzyzcjy** [comment]
@kevmoo Thanks! However, it is not automated...?

**Comment by kevmoo** [comment]
Doing this in an automated way would be very complex. we are actively
avoiding adding a lot of new complexity to this package just to make sure
maintenance stays consistent.

**Comment by fzyzcjy** [comment]
Ah fine... So I may implement it by myself. Thanks

**Comment by fzyzcjy** [comment]
P.S. My proposal on syntax and implementations:

1. Annotate the subclasses

```
@Subclasses([Dog, Human])
abstract class Animal {}
```

2. Then use this directly in the code generator (just some rough idea, not runnable code):

```
List<Type> subclasses = getTheSubclassesAnnotation();
writeDownTheCode('switch(data.type) {');
for(var subclass in subclasses) {
    writeDownTheCode('case $subclass: return $subclass.toJson();');
}
writeDownTheCode('}');
```
