### ISSUE TITLE
JsonSerialization: option on fields/properties to omit empty List/Map

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/json_serializable#6]
_From @kevmoo on October 28, 2016 21:29_

_Copied from original issue: dart-lang/source_gen#96_

**Comment by lukepighetti** [comment]
Requesting an update on this. I have not found a way to gracefully handle empty lists with `json_serializable`

**Comment by kevmoo** [comment]
I've actually started on this. It's a bit gnarly

**Comment by lukepighetti** [comment]
What's the strategy? I assumed, obviously wrongly, that it would be straightforward.

**Comment by kevmoo** [comment]
I've tried hard to make every option round trip cleanly. There are more
interactions with existing options than you might guess...

**Comment by kevmoo** [comment]
I'm looking into this some more – and realized I need to refresh the testing story before I add more things to the matrix of features. Stay tuned...
