### ISSUE TITLE
json serializable objects are not automatically serialized when used as fields of a JsonSerializable class

### ISSUE THREAD

**Issue by ramsestom** [dart-lang/json_serializable#601]
I have a geojson dart library with geojson geometries defined as objects that all implements a 
`Map<String, dynamic> toJson()` method so as a `.fromJson(Map<String, dynamic> json)` constructor. 
For example, I have a `Point` object with a `Point.fromJson(Map<String, dynamic> json)` constructor and a `Map<String, dynamic> toJson()` method
The problem is that, if I use one of these objects as fields of a JsonSerializable class, like for example a `Place` class defined like this:
```
@JsonSerializable()
class Place {
    Point position;
}
```
the `_$PlaceFromJson(Map<String, dynamic> json)` created by the generator correctly call the `.fromJson()` constructor (
```
val.position = json['position'] == null
      ? null
      : Point.fromJson(json['position'] as Map<String, dynamic>);
```
) but the `_$PlaceToJson(Place instance)` method created by the generator do not call the `toJson()` method of `Point` class (`'position': instance.position` so the `Point` object is not serialized, it is only stored as a row object). As a consequence, if you try to serialize and deserialize a `Place ` instance, you end up with this error: 

> Unhandled Exception: type 'Point' is not a subtype of type 'Map<String, dynamic>' in type cast

So I think the generator should automatically make calls to the `toJson()` method of an object in the `_$[class]ToJson` function if this method exists, like it is automatically calling the `fromJson() ` 
constructor into the `_$[class]FromJson` if it exists.

**Comment by ramsestom** [comment]
Ok I found that you actually have to set the `explicitToJson` config flag to true to have the expected behavior.
But why is this flag false by default? It doesn't make any sense!
The documentation state that it is off by default as 
> When using JSON encoding support in dart:convert, toJson is automatically called on objects
but would the json encoder from dart:convert fail if this flag is set to true? No (the json serializable objects would already be fully serialized so the json converter from dart:convert would not have to make any call to `toJson`)
On the other end, if this flag is set to false, calling something like `Place.fromJson(Place.toJson())` woud miserably fail (if `Place` contains another serializable json object like in my example).
So the `explicitToJson` flag should really be `true` by default

**Comment by kevmoo** [comment]
> So the `explicitToJson` flag should really be `true` by default!

I respectfully disagree. Having `toJson` be lazy means we avoid generating a lot of objects until they are needed – this minimizes memory usage, especially for large objects.

**Comment by ramsestom** [comment]
then it's not a `toJson` method. Because json is supposed to contain only maps and lists of Strings, numbers and booleans. Not arbritary objects. 
And usually, if you call a `toJson` method, it is to completely serialize the object, so you would end up creating your objects anyway (the json encoder of dart:convert would create them when you encode it). That is why the  `explicitToJson` flag should be on by default (and could be turned off for edge cases where you need to preserve memory. It should be a parametter of the automatically generated `_$[class]ToJson` method rather than a global config flag bytheway because you may want to fully serialize an member of a json_serializable class in some part of your code and not in another, which isn't currently possible with a class config flag)

**Comment by kevmoo** [comment]
@ramsestom – I'm *absolutely* sympathetic to your argument here.

Sadly, we're well into stable releases and changing this default would be a non-trivial breaking change for many users.

**Comment by ramsestom** [comment]
FYI . Concerning the possibility to set the `explicitToJson` flag at the `_$[class]ToJson` level, I just made a non breaking patch into my fork allowing this (the `_$[class]ToJson` now has an optional explicitToJson allowing to override the `explicitToJson` flag defined at the class config level).
I did not make a pull request as this patch is a bit dirty (the structure of the generator was not really suitable to pass method parametters to the serializer) but you can probably implement the idea a little more rigorously
