### ISSUE TITLE
_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>'

### ISSUE THREAD

**Issue by namndev** [dart-lang/json_serializable#605]
I resolved:
Instead of `json['abc'] as Map<String, dynamic>`, I used
`Map<String, dynamic>.from(json['abc'])`

**Comment by Schoonology** [comment]
I just ran into this same issue, and another safe option seems to be generating `(json['field'] as Map).cast<String, dynamic>()` in place of `json['field'] as Map<String, dynamic>`.

What are the downsides to an approach like this?

**Comment by kevmoo** [comment]
The `cast` call returns a wrapper around the original map which intercepts all calls. So you pay for indirection.

That _should_ be the only downside.

**Comment by kevmoo** [comment]
@namndev , @Schoonology – guessing you guys are both using Flutter here?

**Comment by Schoonology** [comment]
@kevmoo Correct for me, at least. I apologize for not specifying.
