### ISSUE TITLE
Double type casting not working with Inherited class

### ISSUE THREAD

**Issue by Thamizhan** [dart-lang/json_serializable#626]
I have a case where product data and order item data have common fields so I decided to create a base product class which is inherited by product and order item classes. 

Please find my classes below

> BaseProduct

```
class BaseProduct {
  int productId;
  String name;
  String weight;
  String origin;
  int loyaltyPoint;
  double price;
  double specialPrice;
  String image;
  String originalImage;
  String foodType;

  BaseProduct(
      this.productId,
      this.name,
      this.weight,
      this.origin,
      this.loyaltyPoint,
      this.price,
      this.specialPrice,
      this.image,
      this.originalImage,
      this.foodType);
}
```

> Product 
```
@JsonSerializable()
class Product extends BaseProduct {
  String calories;
  String description;

  Product(
      {productId,
      name,
      weight,
      this.calories,
      origin,
      loyaltyPoint,
      this.description,
      price,
      specialPrice,
      image,
      originalImage,
      foodType})
      : super(
            productId,
            name,
            weight,
            origin,
            loyaltyPoint,
            price,
            specialPrice,
            image,
            originalImage,
            foodType);

  factory Product.fromJson(Map<String, dynamic> json) =>
      _$ProductFromJson(json);

  Map<String, dynamic> toJson() => _$ProductToJson(this);
}
```

Everything works fine except double fields from base class. In above example `price` and `specialPrice` are double from `BaseProduct` class.
I'm getting following error when parsing value from API.

> type 'int' is not a subtype of type 'double' dart

I have spend lot of time checking this issue root cause, when I move those fields to my sub class its working fine but not with parent class. 

When I checked in _$ProductFromJson method in generated file I see the difference.
If those fields are in parent class (BaseProduct) it read as 
```
price: json['price'],
specialPrice: json['specialPrice'],
```

but If I put them on same same class (Product) itself it read as
```
price: (json['price'] as num)?.toDouble(),
specialPrice: (json['price'] as num)?.toDouble()
```

So the real problem here is double fields are read is num and convert it to Double but with parent class it just read the value and pass it to constructor. 

**Workaround:**
As a workaround I'm converting price and specialPrice values to double when passing to parent class constructor as below
```
super(
            productId,
            name,
            weight,
            origin,
            loyaltyPoint,
            (price as num).toDouble(),
            (specialPrice as num).toDouble(),
            image,
            originalImage,
            foodType);
```

By doing this I'm not getting any issues and app worked as expected.

I just want to know this is real issue or I'm doing something wrong here.

**Note:**
Same problem with Strings
`name: json['name'] as String` - within same class
`name: json['name']` - from parent class.

But with strings there is no problem arise because string is always received as string. But in case of double it might have values 2 or 2.1.

**Comment by kevmoo** [comment]
Include types in your Product constructor! This is required!


```dart
@JsonSerializable()
class Product extends BaseProduct {
  String calories;
  String description;

  Product(
      {int productId,
      String name,
      String weight,
      this.calories,
      String origin,
      int loyaltyPoint,
      this.description,
      double price,
      double specialPrice,
      String image,
      String originalImage,
      String foodType})
      : super(
            productId,
            name,
            weight,
            origin,
            loyaltyPoint,
            price,
            specialPrice,
            image,
            originalImage,
            foodType);

  factory Product.fromJson(Map<String, dynamic> json) =>
      _$ProductFromJson(json);

  Map<String, dynamic> toJson() => _$ProductToJson(this);
}
```

**Comment by Thamizhan** [comment]
Thanks @kevmoo
