### ISSUE TITLE
Does not generate .g.dart files. Help me solve it.

### ISSUE THREAD

**Issue by poshan0126** [dart-lang/json_serializable#628]
import 'package:moor_flutter/moor_flutter.dart';
import '../app_database/app_database.dart';

part 'account.g.dart';

class Accounts extends Table {
  IntColumn get id => integer().autoIncrement()();

  TextColumn get name => text()();

  TextColumn get nameNepali => text()();

  RealColumn get amount => real().withDefault(Constant(0))();

  BoolColumn get isSystem => boolean().withDefault(Constant(false))();

  DateTimeColumn get createdDate =>
      dateTime().withDefault(currentDateAndTime)();

  DateTimeColumn get modifiedDate =>
      dateTime().withDefault(currentDateAndTime)();

  TextColumn get adminName => text()();

  IntColumn get serialNumber => integer()();

  IntColumn get accountCategoryId =>
      integer().customConstraint('REFERENCES account_categories(id)')();
}

**Comment by kevmoo** [comment]
You must annotate your class with `@JsonSerializable` from `package:json_annotation`

See https://github.com/dart-lang/json_serializable/tree/master/example

**Comment by vadimlukutin** [comment]
I was but it didnt help me

**Comment by vadimlukutin** [comment]
import 'package:json_annotation/json_annotation.dart';
import 'package:collection/collection.dart';

import 'package:chopper/chopper.dart';
import 'package:chopper/chopper.dart' as chopper;

part 'root_api_docs.swagger.chopper.dart';
part 'root_api_docs.swagger.g.dart'; // didnt generate in swagger_dart_code_generator

**Comment by kevmoo** [comment]
Show me your class definition and the error you get...
