### ISSUE TITLE
defaultValue double.nan turns into `NaN`

### ISSUE THREAD

**Issue by lucacasonato** [dart-lang/json_serializable#629]
**Version**: Dart VM version: 2.7.2 (Unknown timestamp) on "linux_x64"

The code
```dart
  @JsonKey(defaultValue: double.nan)
  double x;
```
gets transformed into
```dart
    x: (json['x'] as num)?.toDouble() ?? NaN,
```

which is incorrect as `NaN` is not a defined identifier. It should be transformed into
```dart
    x: (json['x'] as num)?.toDouble() ?? double.nan,
```

**Comment by kevmoo** [comment]
The fix for this has been published https://pub.dev/packages/json_serializable/versions/3.4.0
