### ISSUE TITLE
Generate public classes instead

### ISSUE THREAD

**Issue by lukepighetti** [dart-lang/json_serializable#635]
Currently we annotate a public class and the backing to/from json classes are generated.

```dart
@JsonSerializable()
class Task {
  final String id;
  final String name;
  final String avatar;
  final String createdAt;

  Task(this.id, this.name, this.avatar, this.createdAt);

  factory Task.fromJson(Map<String, dynamic> json) => _$TaskFromJson(json);
  Map<String, dynamic> toJson() => _$TaskToJson(this);
}
```

Is there any reason why we cannot annotate a private class and have `json_serializable` generate the public class? This private class would generate the above public class. The benefit would be less boilerplate. The private class would implemented by the public class.

```dart
@JsonSerializable()
abstract class _Task {
  final String id;
  final String name;
  final String avatar;
  final String createdAt;
}
```

**Comment by lukecaan** [comment]
Agreed!! Going through having to manually type a `toJson` and `fromJson` method for all of my redux actions is really annoying when the generator could just as easily be generating them for me! 

If there was an extra parameter in the annotation like `generatePublicMethods:bool` that'd be awesome

**Comment by kevmoo** [comment]
We likely won't do any work here – and wait for partial class support https://github.com/dart-lang/language/issues/252
