### ISSUE TITLE
why not generate fromJson and toJson functions in the *.g.dart file?

### ISSUE THREAD

**Issue by ISimplifyComplexity** [dart-lang/json_serializable#647]
So I'm using your library and the files are generating just fine. 

I'm wondering though... I've got the following class: 

``` dart
import 'package:flutter/material.dart';
import 'package:json_annotation/json_annotation.dart';
import './product.dart';

part 'product_group.g.dart';

@JsonSerializable(nullable: false)
class ProductGroup {
  final List<Product> products;

  ProductGroup({this.products});

  factory ProductGroup.fromJson(Map<String, dynamic> json) =>
      _$ProductGroupFromJson(json);

  Map<String, dynamic> toJson() => _$ProductGroupToJson(this);
}
```

All my models are going to have the same factory method and toJson methods. Would it not be better to just generate these in the .g.dart file?

**Comment by Tinhorn** [comment]
You might want to pass in another parameter  when you are creating from jsoni.e
`
  Map<String, dynamic> json toJson(Foo foo) => _$ProductGroupToJson(this)..foo = foo;
`
It wouldn't hurt to have an option to generate a reasonable default which does

`
  Map<String, dynamic> toJson() => _$ProductGroupToJson(this);`

**Comment by kevmoo** [comment]
We cannot do this until the language supports something like partial classes - https://github.com/dart-lang/language/issues/252

**Comment by baoxiehao** [comment]
> So I'm using your library and the files are generating just fine.
> 
> I'm wondering though... I've got the following class:
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:json_annotation/json_annotation.dart';
> import './product.dart';
> 
> part 'product_group.g.dart';
> 
> @JsonSerializable(nullable: false)
> class ProductGroup {
>   final List<Product> products;
> 
>   ProductGroup({this.products});
> 
>   factory ProductGroup.fromJson(Map<String, dynamic> json) =>
>       _$ProductGroupFromJson(json);
> 
>   Map<String, dynamic> toJson() => _$ProductGroupToJson(this);
> }
> ```
> 
> All my models are going to have the same factory method and toJson methods. Would it not be better to just generate these in the .g.dart file?

I have the same problem with you. Mostly the default fromJson toJson are working fine. If I should have a different toJson (like fooToJson) I can just name a new method, why not?

**Comment by ISimplifyComplexity** [comment]
> We cannot do this until the language supports something like partial classes - https://github.com/dart-lang/language/issues/252

Oh I assumed that's what the "part" was doing.
