### ISSUE TITLE
classes inheriting  

### ISSUE THREAD

**Issue by baraaaljabban** [dart-lang/json_serializable#649]
Hi, I don't know if this is an issue or not but at least  I have question I hope I can find an answer 
I have the following two classes which one is extending from the other like this : 

```
@JsonSerializable(nullable: true)
class Response {
  final String responseCode;
  final String responseMessage;
  final String errorLog;
  Response({this.errorLog, this.responseCode, this.responseMessage});
  factory Response.fromJson(Map<String, dynamic> json) =>
      _$ResponseFromJson(json);
}
```

```
@JsonSerializable(nullable: false)
class Verify extends Response {
  Data data;
  Verify({
    this.data,
  });
  factory Verify.fromJson(Map<String, dynamic> json) => _$VerifyFromJson(json);
  Map<String, dynamic> toJson() => _$VerifyToJson(this);
}
```

and whenever I'm trying to read **response** class properties it's always **null** so why is this happening , am I doing something wrong here?

from and to json are like 
```
Verify _$VerifyFromJson(Map<String, dynamic> json) {
  return Verify(
    data: Data.fromJson(json['data'] as Map<String, dynamic>),
  );
}

Map<String, dynamic> _$VerifyToJson(Verify instance) => <String, dynamic>{
      'data': instance.data,
    };
```
is there any way to achieve this without writing it manually everywhere ?
thank you for your time for reading this.

**Comment by baraaaljabban** [comment]
thank you for taking time to answer the question and sorry for the inconvenience.

**Comment by intoxicated** [comment]
@kevmoo no other option but write every single of properties to pass into base class? 😢
