### ISSUE TITLE
Avoid runtime JsonSerializable checks in production not debug

### ISSUE THREAD

**Issue by Nolence** [dart-lang/json_serializable#654]
Hi!

I want to update the models in my database but I don't want to cause issues/errors for existing users. For example, if I add a field to the Profile model, I'm afraid JsonSerializable will throw an error as I have disallowUnrecognizedKeys set to true.

I also don't want to remove disallowUnrecognizedKeys completely as it's useful for debugging. At first I tried this:

```dart
@JsonSerializable(disallowUnrecognizedKeys: kDebugMode)
class Profile {}
```

but then I realized that that is likely just a flag for the buildrunner and would generate the code with whatever kDebugMode happens to be at that one point in time.

Is this possible?

**Comment by kevmoo** [comment]
Sadly, no clean way to this – other than flipping the bit before you deploy.

**Comment by Nolence** [comment]
Forgot about this for a while but here's what I've been doing in case anyone else needs it.

1. Make a `build.develop.yaml` and a `build.release.yaml` with the configurations you want. These will replace the `build.yaml` so you can remove that one.
2. Make a `build.sh` file that looks like this:
```sh
flutter pub run build_runner build --delete-conflicting-outputs --config release

flutter build $1

echo "Build complete... Returning models to development"

flutter pub run build_runner build --delete-conflicting-outputs --config develop
```
3. Add executable permission and run like this like this: `./build.sh ios`
