### ISSUE TITLE
Not clear how to use this (these?) packages

### ISSUE THREAD

**Issue by sethladd** [dart-lang/json_serializable#79]
These packages seem great, but it's not clear how to use them? Neither the repo nor the two package READMEs provide step-by-step instructions. They seem to assume that I know things I probably don't :)

Would love to share these with Flutter ecosystem, but would like first to point people to usage instructions.

Thanks!

**Comment by dwaindibbly** [comment]
it's a bit like using `dson`. which does the same thing, except `dson` is easier to use.

**Comment by dwaindibbly** [comment]
to use it (basically) :
 1) import the lib
 2) put `library whatever;` at the top of the file
 3) add a `part 'filename.g.dart'` after the `import`s
 4) create a `build.dart` file (which consists of a `build_runner` and `package:lib/action.dart` (or whatever), then in `main` put `build([actionName(/*actionArgs*/)])` presto)
 5) annotate the classes that you want to serialize with the specified serialization annotation and make sure they extend `_$classNameBlaBlaBlaWhateverIdk`
 6) `dart build.dart`

if you want better instructions, use the dson instructions. and dson. please.

**Comment by kevmoo** [comment]
Tried to address this RE https://github.com/dart-lang/json_serializable/issues/84
