### ISSUE TITLE
Not clear if this is an officially supported package?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/json_serializable#82]
Is this an experiment? Supported by Dart? _the_ way to do JSON? Should Flutter users use this?

Can we be more clear about what this is, in the README?

(a lot of people are excited for better JSON, I want to clearly set expectations if possible. Thanks!)

**Comment by dwaindibbly** [comment]
I wonder why this exists in the first place. just look at `dson`! or... `dson`, `serializable` and `built_mirrors`. they already do this. and my fork of the three is this and more!

**Comment by DanTup** [comment]
I'd love to know the answer to this too - JSON has always one of my gripes with Dart. Is this package a reasonable thing to start with?

**Comment by kevmoo** [comment]
We use this in several internal and external projects. It's updated to stay in sync with changes to the SDK and related packages (source_gen, build, etc).

We fix bugs as they are found, but feature work is mostly driven by internal needs.

If community folks want to extend functionality, though, pull requests are welcome!
