### ISSUE TITLE
Requesting more prescriptive README for example w.r.t. script

### ISSUE THREAD

**Issue by sethladd** [dart-lang/json_serializable#84]
The README in the example says "create the scripts to run code generation", but I don't know how to take action on that. Can we be more prescriptive? I know you link to the tool/ directory but can you be more specific?

What's the MVP step-by-step I need to do in order to use this? Cut-n-paste style :)

For example, do I need all three of the scripts you mention? Do I pick one to start? Do I just copy and paste these three scripts into my app? Where would I paste these script into?

**Comment by dwaindibbly** [comment]
it's basically where you import the build_runner package along with the json_serializable's action.dart, then in main you just put `build([whateverAction(['lib/**.dart'])])` or whatever.

or, y'know, just use dson. which actually tells you what to do.

**Comment by kevmoo** [comment]
We point everyone to the example package: https://github.com/dart-lang/json_serializable/tree/master/example

We try to be very clear/prescriptive.

The new `build_runner` logic also makes this much easier.
