### ISSUE TITLE
Why does this package exist?

### ISSUE THREAD

**Issue by dwaindibbly** [dart-lang/json_serializable#89]
because `dson` exists already.

**Comment by matanlurey** [comment]
Thank you for your passion.

As you can imagine there is no such thing as "one size fits all" in programming, the web, or computer science generally. While we're really excited that the community has found lots of packages useful, including `dson`, the rationale for this package has been for a while mostly testing new build infrastructure (it uses to be _part_ of `package:source_gen`). 

Happy holidays!

**Comment by dwaindibbly** [comment]
i thought **flutter** was supposed to be like "one size fits all". or at least "pretty much fits what it's meant to fit".

**Comment by matanlurey** [comment]
I don't know what this has to do with Flutter.
